'''
List of systematics
'''

    ## individual types
lep_sys = [
    'Lep_RECOUp', 'Lep_RECODown',
    'Lep_TRIGUp', 'Lep_TRIGDown'
]

btag_sys = [
    'btag_bc_UP', 'btag_bc_DW',
    'btag_l_UP', 'btag_l_DW',
]

jet_sys = [
    'JER_UP', 'JER_DW',
    'JES_UP', 'JES_DW',
    'MET_UP', 'MET_DW',
]

misc_sys = [
    'PileupUp', 'PileupDown',
]

prefire_sys = ['PrefireUp', 'PrefireDown']

ps_sys = [
    'ISRUp', 'ISRDown',
    'FSRUp', 'FSRDown',
]

lhe_sys = [
    'FACTORUp', 'FACTORDown',
    'RENORMUp', 'RENORMDown',
    'RENORM_FACTOR_SAMEUp', 'RENORM_FACTOR_SAMEDown',
    'RENORM_FACTOR_DIFFUp', 'RENORM_FACTOR_DIFFDown',
]
    ## groups
reweight_sys = {
    '2016' : lep_sys + btag_sys + misc_sys + prefire_sys,
    '2017' : lep_sys + btag_sys + misc_sys + prefire_sys,
    '2018' : lep_sys + btag_sys + misc_sys
}

event_sys = {
    '2016' : jet_sys,
    '2017' : jet_sys,
    '2018' : jet_sys
}

ttJets_sys = {
    'ISR_UP' : 'ISRUp',
    'ISR_DW' : 'ISRDown',
    'FSR_UP' : 'FSRUp',
    'FSR_DW' : 'FSRDown',
    'FACTOR_UP' : 'FACTORUp',
    'FACTOR_DW' : 'FACTORDown',
    'RENORM_UP' : 'RENORMUp',
    'RENORM_DW' : 'RENORMDown',
    'RENORM_FACTOR_UP' : 'RENORM_FACTOR_SAMEUp',
    'RENORM_FACTOR_DW' : 'RENORM_FACTOR_SAMEDown',
    'RENORM_UP_FACTOR_DW' : 'RENORM_FACTOR_DIFFUp',
    'RENORM_DW_FACTOR_UP' : 'RENORM_FACTOR_DIFFDown',
    'MTOP_UP' : 'mtopUP',
    'MTOP_DW' : 'mtopDOWN',
    'HDAMP_UP' : 'hdampUP',
    'HDAMP_DW' : 'hdampDOWN',
    'UE_UP' : 'ueUP',
    'UE_DW' : 'ueDOWN',
    'fsr_UP'  : 'fsrUP',
    'fsr_DW': 'fsrDOWN',
    'isr_UP'  : 'isrUP',
    'isr_DW': 'isrDOWN',
    'MTOP_1695': 'mtop1695',
    'MTOP_1755': 'mtop1755',
    
}

# dict of name_I_want : name_in_code
reweight_sys_opts = {
    '2016' : {
        'LEP_RECO_UP' : 'Lep_RECOUp',
        'LEP_RECO_DW' : 'Lep_RECODown',
        'LEP_TRIG_UP' : 'Lep_TRIGUp',
        'LEP_TRIG_DW' : 'Lep_TRIGDown',
        'BTAG_BC_UP' : 'btag_bc_UP',
        'BTAG_BC_DW' : 'btag_bc_DW',
        'BTAG_L_UP' : 'btag_l_UP',
        'BTAG_L_DW' : 'btag_l_DW',
        'PILEUP_UP' : 'PileupUp',
        'PILEUP_DW' : 'PileupDown',
        'PREFIRE_UP' : 'PrefireUp',
        'PREFIRE_DW' : 'PrefireDown',
        'ISR_UP' : 'ISRUp',
        'ISR_DW' : 'ISRDown',
        'FSR_UP' : 'FSRUp',
        'FSR_DW' : 'FSRDown',
        'FACTOR_UP' : 'FACTORUp',
        'FACTOR_DW' : 'FACTORDown',
        'RENORM_UP' : 'RENORMUp',
        'RENORM_DW' : 'RENORMDown',
        'RENORM_FACTOR_UP' : 'RENORM_FACTOR_SAMEUp',
        'RENORM_FACTOR_DW' : 'RENORM_FACTOR_SAMEDown',
        'RENORM_UP_FACTOR_DW' : 'RENORM_FACTOR_DIFFUp',
        'RENORM_DW_FACTOR_UP' : 'RENORM_FACTOR_DIFFDown',
    },
    '2017' : {
        'LEP_RECO_UP' : 'Lep_RECOUp',
        'LEP_RECO_DW' : 'Lep_RECODown',
        'LEP_TRIG_UP' : 'Lep_TRIGUp',
        'LEP_TRIG_DW' : 'Lep_TRIGDown',
        'BTAG_BC_UP' : 'btag_bc_UP',
        'BTAG_BC_DW' : 'btag_bc_DW',
        'BTAG_L_UP' : 'btag_l_UP',
        'BTAG_L_DW' : 'btag_l_DW',
        'PILEUP_UP' : 'PileupUp',
        'PILEUP_DW' : 'PileupDown',
        'PREFIRE_UP' : 'PrefireUp',
        'PREFIRE_DW' : 'PrefireDown',
        'ISR_UP' : 'ISRUp',
        'ISR_DW' : 'ISRDown',
        'FSR_UP' : 'FSRUp',
        'FSR_DW' : 'FSRDown',
        'FACTOR_UP' : 'FACTORUp',
        'FACTOR_DW' : 'FACTORDown',
        'RENORM_UP' : 'RENORMUp',
        'RENORM_DW' : 'RENORMDown',
        'RENORM_FACTOR_UP' : 'RENORM_FACTOR_SAMEUp',
        'RENORM_FACTOR_DW' : 'RENORM_FACTOR_SAMEDown',
        'RENORM_UP_FACTOR_DW' : 'RENORM_FACTOR_DIFFUp',
        'RENORM_DW_FACTOR_UP' : 'RENORM_FACTOR_DIFFDown',
    },
    '2018' : {
        'LEP_RECO_UP' : 'Lep_RECOUp',
        'LEP_RECO_DW' : 'Lep_RECODown',
        'LEP_TRIG_UP' : 'Lep_TRIGUp',
        'LEP_TRIG_DW' : 'Lep_TRIGDown',
        'BTAG_BC_UP' : 'btag_bc_UP',
        'BTAG_BC_DW' : 'btag_bc_DW',
        'BTAG_L_UP' : 'btag_l_UP',
        'BTAG_L_DW' : 'btag_l_DW',
        'PILEUP_UP' : 'PileupUp',
        'PILEUP_DW' : 'PileupDown',
        'ISR_UP' : 'ISRUp',
        'ISR_DW' : 'ISRDown',
        'FSR_UP' : 'FSRUp',
        'FSR_DW' : 'FSRDown',
        'FACTOR_UP' : 'FACTORUp',
        'FACTOR_DW' : 'FACTORDown',
        'RENORM_UP' : 'RENORMUp',
        'RENORM_DW' : 'RENORMDown',
        'RENORM_FACTOR_UP' : 'RENORM_FACTOR_SAMEUp',
        'RENORM_FACTOR_DW' : 'RENORM_FACTOR_SAMEDown',
        'RENORM_UP_FACTOR_DW' : 'RENORM_FACTOR_DIFFUp',
        'RENORM_DW_FACTOR_UP' : 'RENORM_FACTOR_DIFFDown',
    },
}
event_sys_opts = {
    '2016' : {
        'JER_UP' : 'JER_UP',
        'JER_DW' : 'JER_DW',
        'JES_UP' : 'JES_UP',
        'JES_DW' : 'JES_DW',
        'MET_UP' : 'MET_UP',
        'MET_DW' : 'MET_DW',
    },
    '2017' : {
        'JER_UP' : 'JER_UP',
        'JER_DW' : 'JER_DW',
        'JES_UP' : 'JES_UP',
        'JES_DW' : 'JES_DW',
        'MET_UP' : 'MET_UP',
        'MET_DW' : 'MET_DW',
    },
    '2018' : {
        'JER_UP' : 'JER_UP',
        'JER_DW' : 'JER_DW',
        'JES_UP' : 'JES_UP',
        'JES_DW' : 'JES_DW',
        'MET_UP' : 'MET_UP',
        'MET_DW' : 'MET_DW',
    },
}


# dict of name_I_want : name_in_code
signal_reweight_opts = {
    '2016' : {
        'LEP_RECO_UP' : 'Lep_RECOUp',
        'LEP_RECO_DW' : 'Lep_RECODown',
        'LEP_TRIG_UP' : 'Lep_TRIGUp',
        'LEP_TRIG_DW' : 'Lep_TRIGDown',
        'BTAG_BC_UP' : 'btag_bc_UP',
        'BTAG_BC_DW' : 'btag_bc_DW',
        'BTAG_L_UP' : 'btag_l_UP',
        'BTAG_L_DW' : 'btag_l_DW',
        'PILEUP_UP' : 'PileupUp',
        'PILEUP_DW' : 'PileupDown',
        'PREFIRE_UP' : 'PrefireUp',
        'PREFIRE_DW' : 'PrefireDown',
        #'ISR_UP' : 'ISRUp',
        #'ISR_DW' : 'ISRDown',
        #'FSR_UP' : 'FSRUp',
        #'FSR_DW' : 'FSRDown',
        #'FACTOR_UP' : 'FACTORUp',
        #'FACTOR_DW' : 'FACTORDown',
        #'RENORM_UP' : 'RENORMUp',
        #'RENORM_DW' : 'RENORMDown',
        #'RENORM_FACTOR_UP' : 'RENORM_FACTOR_SAMEUp',
        #'RENORM_FACTOR_DW' : 'RENORM_FACTOR_SAMEDown',
        #'RENORM_UP_FACTOR_DW' : 'RENORM_FACTOR_DIFFUp',
        #'RENORM_DW_FACTOR_UP' : 'RENORM_FACTOR_DIFFDown',
    },
    '2017' : {
        'LEP_RECO_UP' : 'Lep_RECOUp',
        'LEP_RECO_DW' : 'Lep_RECODown',
        'LEP_TRIG_UP' : 'Lep_TRIGUp',
        'LEP_TRIG_DW' : 'Lep_TRIGDown',
        'BTAG_BC_UP' : 'btag_bc_UP',
        'BTAG_BC_DW' : 'btag_bc_DW',
        'BTAG_L_UP' : 'btag_l_UP',
        'BTAG_L_DW' : 'btag_l_DW',
        'PILEUP_UP' : 'PileupUp',
        'PILEUP_DW' : 'PileupDown',
        'PREFIRE_UP' : 'PrefireUp',
        'PREFIRE_DW' : 'PrefireDown',
        #'ISR_UP' : 'ISRUp',
        #'ISR_DW' : 'ISRDown',
        #'FSR_UP' : 'FSRUp',
        #'FSR_DW' : 'FSRDown',
        #'FACTOR_UP' : 'FACTORUp',
        #'FACTOR_DW' : 'FACTORDown',
        #'RENORM_UP' : 'RENORMUp',
        #'RENORM_DW' : 'RENORMDown',
        #'RENORM_FACTOR_UP' : 'RENORM_FACTOR_SAMEUp',
        #'RENORM_FACTOR_DW' : 'RENORM_FACTOR_SAMEDown',
        #'RENORM_UP_FACTOR_DW' : 'RENORM_FACTOR_DIFFUp',
        #'RENORM_DW_FACTOR_UP' : 'RENORM_FACTOR_DIFFDown',
    },
    '2018' : {
        'LEP_RECO_UP' : 'Lep_RECOUp',
        'LEP_RECO_DW' : 'Lep_RECODown',
        'LEP_TRIG_UP' : 'Lep_TRIGUp',
        'LEP_TRIG_DW' : 'Lep_TRIGDown',
        'BTAG_BC_UP' : 'btag_bc_UP',
        'BTAG_BC_DW' : 'btag_bc_DW',
        'BTAG_L_UP' : 'btag_l_UP',
        'BTAG_L_DW' : 'btag_l_DW',
        'PILEUP_UP' : 'PileupUp',
        'PILEUP_DW' : 'PileupDown',
        #'ISR_UP' : 'ISRUp',
        #'ISR_DW' : 'ISRDown',
        #'FSR_UP' : 'FSRUp',
        #'FSR_DW' : 'FSRDown',
        #'FACTOR_UP' : 'FACTORUp',
        #'FACTOR_DW' : 'FACTORDown',
        #'RENORM_UP' : 'RENORMUp',
        #'RENORM_DW' : 'RENORMDown',
        #'RENORM_FACTOR_UP' : 'RENORM_FACTOR_SAMEUp',
        #'RENORM_FACTOR_DW' : 'RENORM_FACTOR_SAMEDown',
        #'RENORM_UP_FACTOR_DW' : 'RENORM_FACTOR_DIFFUp',
        #'RENORM_DW_FACTOR_UP' : 'RENORM_FACTOR_DIFFDown',
    },
}



# dict of systematic in analyzer to plotting name
sys_to_name = {
    '2016' : {
        'nosys' : 'nosys',
        'Lep_RECOUp'   : 'LEP_RECO_UP',
        'Lep_RECODown' : 'LEP_RECO_DW',
        'Lep_TRIGUp'   : 'LEP_TRIG_UP',
        'Lep_TRIGDown' : 'LEP_TRIG_DW',
        'btag_bc_UP' : 'BTAG_BC_UP',
        'btag_bc_DW' : 'BTAG_BC_DW',
        'btag_l_UP'  : 'BTAG_L_UP',
        'btag_l_DW'  : 'BTAG_L_DW',
        'PileupUp'  : 'PILEUP_UP',
        'PileupDown': 'PILEUP_DW',
        'PrefireUp' : 'PREFIRE_UP',
        'PrefireDown' : 'PREFIRE_DW',
        'ISRUp'  : 'ISR_UP',
        'ISRDown': 'ISR_DW',
        'FSRUp'  : 'FSR_UP',
        'FSRDown': 'FSR_DW',
        'FACTORUp'  : 'FACTOR_UP',
        'FACTORDown': 'FACTOR_DW',
        'RENORMUp'  : 'RENORM_UP',
        'RENORMDown': 'RENORM_DW',
        'RENORM_FACTOR_SAMEUp'  : 'RENORM_FACTOR_UP',
        'RENORM_FACTOR_SAMEDown': 'RENORM_FACTOR_DW',
        'RENORM_FACTOR_DIFFUp'  : 'RENORM_UP_FACTOR_DW',
        'RENORM_FACTOR_DIFFDown': 'RENORM_DW_FACTOR_UP',
        'mtopUP'  : 'MTOP_UP',
        'mtopDOWN': 'MTOP_DW',
        'hdampUP'  : 'HDAMP_UP',
        'hdampDOWN': 'HDAMP_DW',
        'ueUP'  : 'UE_UP',
        'ueDOWN': 'UE_DW',
        'JER_UP' : 'JER_UP',
        'JER_DW' : 'JER_DW',
        'JES_UP' : 'JES_UP',
        'JES_DW' : 'JES_DW',
        'MET_UP' : 'MET_UP',
        'MET_DW' : 'MET_DW',
        'fsrUP'  : 'sampleFSR_UP',
        'fsrDOWN': 'sampleFSR_DW',
        'isrUP'  : 'sampleISR_UP',
        'isrDOWN': 'sampleISR_DW',
        'mtop1695': 'MTOP3GeV_DW',
        'mtop1755': 'MTOP3GeV_UP',
    },
    '2017' : {
        'nosys' : 'nosys',
        'Lep_RECOUp'   : 'LEP_RECO_UP',
        'Lep_RECODown' : 'LEP_RECO_DW',
        'Lep_TRIGUp'   : 'LEP_TRIG_UP',
        'Lep_TRIGDown' : 'LEP_TRIG_DW',
        'btag_bc_UP' : 'BTAG_BC_UP',
        'btag_bc_DW' : 'BTAG_BC_DW',
        'btag_l_UP'  : 'BTAG_L_UP',
        'btag_l_DW'  : 'BTAG_L_DW',
        'PileupUp'  : 'PILEUP_UP',
        'PileupDown': 'PILEUP_DW',
        'PrefireUp' : 'PREFIRE_UP',
        'PrefireDown' : 'PREFIRE_DW',
        'ISRUp'  : 'ISR_UP',
        'ISRDown': 'ISR_DW',
        'FSRUp'  : 'FSR_UP',
        'FSRDown': 'FSR_DW',
        'FACTORUp'  : 'FACTOR_UP',
        'FACTORDown': 'FACTOR_DW',
        'RENORMUp'  : 'RENORM_UP',
        'RENORMDown': 'RENORM_DW',
        'RENORM_FACTOR_SAMEUp'  : 'RENORM_FACTOR_UP',
        'RENORM_FACTOR_SAMEDown': 'RENORM_FACTOR_DW',
        'RENORM_FACTOR_DIFFUp'  : 'RENORM_UP_FACTOR_DW',
        'RENORM_FACTOR_DIFFDown': 'RENORM_DW_FACTOR_UP',
        'mtopUP'  : 'MTOP_UP',
        'mtopDOWN': 'MTOP_DW',
        'hdampUP'  : 'HDAMP_UP',
        'hdampDOWN': 'HDAMP_DW',
        'ueUP'  : 'UE_UP',
        'ueDOWN': 'UE_DW',
        'JER_UP' : 'JER_UP',
        'JER_DW' : 'JER_DW',
        'JES_UP' : 'JES_UP',
        'JES_DW' : 'JES_DW',
        'MET_UP' : 'MET_UP',
        'MET_DW' : 'MET_DW',
        'mtop1695': 'MTOP3GeV_DW',
        'mtop1755': 'MTOP3GeV_UP',
    },
    '2018' : {
        'nosys' : 'nosys',
        'Lep_RECOUp'   : 'LEP_RECO_UP',
        'Lep_RECODown' : 'LEP_RECO_DW',
        'Lep_TRIGUp'   : 'LEP_TRIG_UP',
        'Lep_TRIGDown' : 'LEP_TRIG_DW',
        'btag_bc_UP' : 'BTAG_BC_UP',
        'btag_bc_DW' : 'BTAG_BC_DW',
        'btag_l_UP'  : 'BTAG_L_UP',
        'btag_l_DW'  : 'BTAG_L_DW',
        'PileupUp'  : 'PILEUP_UP',
        'PileupDown': 'PILEUP_DW',
        'ISRUp'  : 'ISR_UP',
        'ISRDown': 'ISR_DW',
        'FSRUp'  : 'FSR_UP',
        'FSRDown': 'FSR_DW',
        'FACTORUp'  : 'FACTOR_UP',
        'FACTORDown': 'FACTOR_DW',
        'RENORMUp'  : 'RENORM_UP',
        'RENORMDown': 'RENORM_DW',
        'RENORM_FACTOR_SAMEUp'  : 'RENORM_FACTOR_UP',
        'RENORM_FACTOR_SAMEDown': 'RENORM_FACTOR_DW',
        'RENORM_FACTOR_DIFFUp'  : 'RENORM_UP_FACTOR_DW',
        'RENORM_FACTOR_DIFFDown': 'RENORM_DW_FACTOR_UP',
        'mtopUP'  : 'MTOP_UP',
        'mtopDOWN': 'MTOP_DW',
        'hdampUP'  : 'HDAMP_UP',
        'hdampDOWN': 'HDAMP_DW',
        'ueUP'  : 'UE_UP',
        'ueDOWN': 'UE_DW',
        'JER_UP' : 'JER_UP',
        'JER_DW' : 'JER_DW',
        'JES_UP' : 'JES_UP',
        'JES_DW' : 'JES_DW',
        'MET_UP' : 'MET_UP',
        'MET_DW' : 'MET_DW',
        'mtop1695': 'MTOP3GeV_DW',
        'mtop1755': 'MTOP3GeV_UP',
    },
}



    ## dict for writing template names
template_sys_to_name = {
        ## format is name_in_analyzer : (extension_to_topology, only_applies_to_TT)
    '2016' : {
        'nosys' : ('', False),
        'JES_UP' : ('CMS_scale_j_13TeVUp', False),
        'JES_DW' : ('CMS_scale_j_13TeVDown', False),
        'JER_UP' : ('CMS_res_j_13TeVUp', False),
        'JER_DW' : ('CMS_res_j_13TeVDown', False),
        'MET_UP' : ('CMS_METunclustered_13TeVUp', False),
        'MET_DW' : ('CMS_METunclustered_13TeVDown', False),
        'btag_bc_UP' : ('CMS_eff_b_13TeVUp', False),
        'btag_bc_DW' : ('CMS_eff_b_13TeVDown', False),
        'btag_l_UP' : ('CMS_fake_b_13TeVUp', False),
        'btag_l_DW' : ('CMS_fake_b_13TeVDown', False),
        'Lep_RECOUp' : ('CMS_eff_reco_LEPUp', False),
        'Lep_RECODown' : ('CMS_eff_reco_LEPDown', False),
        'Lep_TRIGUp' : ('CMS_eff_trigger_LEPUp', False),
        'Lep_TRIGDown' : ('CMS_eff_trigger_LEPDown', False),
        'PileupUp' : ('CMS_pileupUp', False),
        'PileupDown' : ('CMS_pileupDown', False),
        'PrefireUp' : ('CMS_prefireUp', False),
        'PrefireDown' : ('CMS_prefireDown', False), 
            # TT systematics
        'FSRUp' : ('FSR_TTUp', True),
        'FSRDown' : ('FSR_TTDown', True),
        'ISRUp' : ('ISR_TTUp', True),
        'ISRDown' : ('ISR_TTDown', True),
        'RENORMUp' : ('QCDscaleMERenorm_TTUp', True),
        'RENORMDown' : ('QCDscaleMERenorm_TTDown', True),
        'FACTORUp' : ('QCDscaleMEFactor_TTUp', True),
        'FACTORDown' : ('QCDscaleMEFactor_TTDown', True),
        'RENORM_FACTOR_SAMEUp' : ('QCDscaleMERenormFactor_TTUp', True),
        'RENORM_FACTOR_SAMEDown' : ('QCDscaleMERenormFactor_TTDown', True),
        'ueUP' : ('UE_TTUp', True),
        'ueDOWN' : ('UE_TTDown', True),
        'hdampUP' : ('Hdamp_TTUp', True),
        'hdampDOWN' : ('Hdamp_TTDown', True),
        'mtopUP' : ('TMassUp', True),
        'mtopDOWN' : ('TMassDown', True),
    },
    '2017' : {
        'nosys' : ('', False),
        'JES_UP' : ('CMS_scale_j_13TeVUp', False),
        'JES_DW' : ('CMS_scale_j_13TeVDown', False),
        'JER_UP' : ('CMS_res_j_13TeVUp', False),
        'JER_DW' : ('CMS_res_j_13TeVDown', False),
        'MET_UP' : ('CMS_METunclustered_13TeVUp', False),
        'MET_DW' : ('CMS_METunclustered_13TeVDown', False),
        'btag_bc_UP' : ('CMS_eff_b_13TeVUp', False),
        'btag_bc_DW' : ('CMS_eff_b_13TeVDown', False),
        'btag_l_UP' : ('CMS_fake_b_13TeVUp', False),
        'btag_l_DW' : ('CMS_fake_b_13TeVDown', False),
        'Lep_RECOUp' : ('CMS_eff_reco_LEPUp', False),
        'Lep_RECODown' : ('CMS_eff_reco_LEPDown', False),
        'Lep_TRIGUp' : ('CMS_eff_trigger_LEPUp', False),
        'Lep_TRIGDown' : ('CMS_eff_trigger_LEPDown', False),
        'PileupUp' : ('CMS_pileupUp', False),
        'PileupDown' : ('CMS_pileupDown', False),
        'PrefireUp' : ('CMS_prefireUp', False),
        'PrefireDown' : ('CMS_prefireDown', False), 
            # TT systematics
        'FSRUp' : ('FSR_TTUp', True),
        'FSRDown' : ('FSR_TTDown', True),
        'ISRUp' : ('ISR_TTUp', True),
        'ISRDown' : ('ISR_TTDown', True),
        'RENORMUp' : ('QCDscaleMERenorm_TTUp', True),
        'RENORMDown' : ('QCDscaleMERenorm_TTDown', True),
        'FACTORUp' : ('QCDscaleMEFactor_TTUp', True),
        'FACTORDown' : ('QCDscaleMEFactor_TTDown', True),
        'RENORM_FACTOR_SAMEUp' : ('QCDscaleMERenormFactor_TTUp', True),
        'RENORM_FACTOR_SAMEDown' : ('QCDscaleMERenormFactor_TTDown', True),
        'ueUP' : ('UE_TTUp', True),
        'ueDOWN' : ('UE_TTDown', True),
        'hdampUP' : ('Hdamp_TTUp', True),
        'hdampDOWN' : ('Hdamp_TTDown', True),
        'mtopUP' : ('TMassUp', True),
        'mtopDOWN' : ('TMassDown', True),
    },
    '2018' : {
        'nosys' : ('', False),
        'JES_UP' : ('CMS_scale_j_13TeVUp', False),
        'JES_DW' : ('CMS_scale_j_13TeVDown', False),
        'JER_UP' : ('CMS_res_j_13TeVUp', False),
        'JER_DW' : ('CMS_res_j_13TeVDown', False),
        'MET_UP' : ('CMS_METunclustered_13TeVUp', False),
        'MET_DW' : ('CMS_METunclustered_13TeVDown', False),
        'btag_bc_UP' : ('CMS_eff_b_13TeVUp', False),
        'btag_bc_DW' : ('CMS_eff_b_13TeVDown', False),
        'btag_l_UP' : ('CMS_fake_b_13TeVUp', False),
        'btag_l_DW' : ('CMS_fake_b_13TeVDown', False),
        'Lep_RECOUp' : ('CMS_eff_reco_LEPUp', False),
        'Lep_RECODown' : ('CMS_eff_reco_LEPDown', False),
        'Lep_TRIGUp' : ('CMS_eff_trigger_LEPUp', False),
        'Lep_TRIGDown' : ('CMS_eff_trigger_LEPDown', False),
        'PileupUp' : ('CMS_pileupUp', False),
        'PileupDown' : ('CMS_pileupDown', False),
            # TT systematics
        'FSRUp' : ('FSR_TTUp', True),
        'FSRDown' : ('FSR_TTDown', True),
        'ISRUp' : ('ISR_TTUp', True),
        'ISRDown' : ('ISR_TTDown', True),
        'RENORMUp' : ('QCDscaleMERenorm_TTUp', True),
        'RENORMDown' : ('QCDscaleMERenorm_TTDown', True),
        'FACTORUp' : ('QCDscaleMEFactor_TTUp', True),
        'FACTORDown' : ('QCDscaleMEFactor_TTDown', True),
        'RENORM_FACTOR_SAMEUp' : ('QCDscaleMERenormFactor_TTUp', True),
        'RENORM_FACTOR_SAMEDown' : ('QCDscaleMERenormFactor_TTDown', True),
        'ueUP' : ('UE_TTUp', True),
        'ueDOWN' : ('UE_TTDown', True),
        'hdampUP' : ('Hdamp_TTUp', True),
        'hdampDOWN' : ('Hdamp_TTDown', True),
        'mtopUP' : ('TMassUp', True),
        'mtopDOWN' : ('TMassDown', True),
    },
}
