"""
List of systematics
"""

ind_jec_sys = {
    year : {
        #"JES_AbsoluteFlavMap",
        #"JES_CorrelationGroupFlavor",
        #"JES_CorrelationGroupIntercalibration",
        #"JES_CorrelationGroupMPFInSitu",
        #"JES_CorrelationGroupUncorrelated",
        #"JES_CorrelationGroupbJES",
        #"JES_FlavorPhotonJet",
        #"JES_FlavorPureBottom",
        #"JES_FlavorPureCharm",
        #"JES_FlavorPureGluon",
        #"JES_FlavorPureQuark",
        #"JES_FlavorZJet",
        #"JES_PileUpEnvelope",
        #"JES_PileUpMuZero",
        #"JES_PileUpPtEC2",
        #"JES_PileUpPtHF",
        #"JES_RelativeJEREC2",
        #"JES_RelativeJERHF",
        #"JES_RelativePtEC2",
        #"JES_RelativePtHF",
        #"JES_RelativeStatHF",
        #"JES_SubTotalAbsolute",
        #"JES_SubTotalMC",
        #"JES_SubTotalPileUp",
        #"JES_SubTotalPt",
        #"JES_SubTotalRelative",
        #"JES_SubTotalScale",
        #"JES_TotalNoFlavor",
        #"JES_TotalNoFlavorNoTime",
        #"JES_TotalNoTime",
        "JES_AbsoluteMPFBias",
        "JES_AbsoluteScale",
        "JES_AbsoluteStat",
        "JES_FlavorQCD",
        "JES_Fragmentation",
        "JES_PileUpDataMC",
        "JES_PileUpPtBB",
        "JES_PileUpPtEC1",
        "JES_PileUpPtRef",
        "JES_RelativeBal",
        "JES_RelativeFSR",
        "JES_RelativeJEREC1",
        "JES_RelativePtBB",
        "JES_RelativePtEC1",
        "JES_RelativeSample",
        "JES_RelativeStatEC",
        "JES_RelativeStatFSR",
        "JES_SinglePionECAL",
        "JES_SinglePionHCAL",
        "JES_TimePtEta",
        "JES_Total",
    }
    for year in ["2016APV", "2016", "2017", "2018"]
}


regroup_jec_sys = {
    year : {
        #"JES_Absolute",
        #f"JES_Absolute_{year}",
        #"JES_BBEC1",
        #f"JES_BBEC1_{year}",
        #"JES_FlavorQCD",
        #"JES_RelativeBal",
        #f"JES_RelativeSample_{year}",
        ##"JES_Total",
        "JES_FlavorQCDOnlyLightJets",
        #"JES_FlavorPureBottom",
        #"JES_FlavorPureCharm",
        #"JES_FlavorPureGluon",
        #"JES_FlavorPureQuark",
        #"JES_FlavorPureBottomOnlyBottomJets",
        #"JES_FlavorPureCharmOnlyCharmJets",
        #"JES_FlavorPureGluonOnlyGluonJets",
        #"JES_FlavorPureQuarkOnlyQuarkJets",
    }
    for year in ["2016APV", "2016", "2017", "2018"]
}


ttJets_sys = {
    "ISR_UP" : "ISRUp",
    "ISR_DW" : "ISRDown",
    "FSR_UP" : "FSRUp",
    "FSR_DW" : "FSRDown",
    "FACTOR_UP" : "FACTORUp",
    "FACTOR_DW" : "FACTORDown",
    "RENORM_UP" : "RENORMUp",
    "RENORM_DW" : "RENORMDown",
    "RENORM_FACTOR_UP" : "RENORM_FACTOR_SAMEUp",
    "RENORM_FACTOR_DW" : "RENORM_FACTOR_SAMEDown",
    "RENORM_UP_FACTOR_DW" : "RENORM_FACTOR_DIFFUp",
    "RENORM_DW_FACTOR_UP" : "RENORM_FACTOR_DIFFDown",
    "MTOP_UP" : "mtopUP",
    "MTOP_DW" : "mtopDOWN",
    "HDAMP_UP" : "hdampUP",
    "HDAMP_DW" : "hdampDOWN",
    "UE_UP" : "ueUP",
    "UE_DW" : "ueDOWN",
    "fsr_UP"  : "fsrUP",
    "fsr_DW": "fsrDOWN",
    "isr_UP"  : "isrUP",
    "isr_DW": "isrDOWN",
    "MTOP3GeV_DW": "mtop1695",
    "MTOP3GeV_UP": "mtop1755",
    "CR1" : "CR1",
    "CR2" : "CR2",
    "erdON" : "erdON",
}

# dict of name_I_want : name_in_code
    # systematics that only change event weights, for nonsignal datasets
reweight_sys_opts = {
    year : {
        "LEP_IDtot_UP" : "Lep_IDtotUp",
        "LEP_IDtot_DW" : "Lep_IDtotDown",
        "LEP_IDstat_UP" : "Lep_IDstatUp",
        "LEP_IDstat_DW" : "Lep_IDstatDown",
        "LEP_IDsyst_UP" : "Lep_IDsystUp",
        "LEP_IDsyst_DW" : "Lep_IDsystDown",
        "LEP_ISOtot_UP" : "Lep_ISOtotUp",
        "LEP_ISOtot_DW" : "Lep_ISOtotDown",
        "LEP_ISOstat_UP" : "Lep_ISOstatUp",
        "LEP_ISOstat_DW" : "Lep_ISOstatDown",
        "LEP_ISOsyst_UP" : "Lep_ISOsystUp",
        "LEP_ISOsyst_DW" : "Lep_ISOsystDown",
        "LEP_TRIGtot_UP" : "Lep_TRIGtotUp",
        "LEP_TRIGtot_DW" : "Lep_TRIGtotDown",
        "LEP_TRIGstat_UP" : "Lep_TRIGstatUp",
        "LEP_TRIGstat_DW" : "Lep_TRIGstatDown",
        "LEP_TRIGsyst_UP" : "Lep_TRIGsystUp",
        "LEP_TRIGsyst_DW" : "Lep_TRIGsystDown",
        "LEP_RECOtot_UP" : "Lep_RECOtotUp",
        "LEP_RECOtot_DW" : "Lep_RECOtotDown",
        #"BTAG_BC_UP" : "btag_bc_up",
        #"BTAG_BC_DW" : "btag_bc_down",
        #"BTAG_BC_JES_UP" : "btag_bc_jes_up",
        #"BTAG_BC_PILEUP_UP" : "btag_bc_pileup_up",
        #"BTAG_BC_STATISTIC_UP" : "btag_bc_statistic_up",
        ##"BTAG_BC_TYPE3_UP" : "btag_bc_type3_up",
                ## type 3 subsources
        "BTAG_BC_BFRAGMENTATION_UP" : "btag_bc_bfragmentation_up",
        "BTAG_BC_BTEMPCORR_UP" : "btag_bc_btempcorr_up",
        "BTAG_BC_CB_UP" : "btag_bc_cb_up",
        "BTAG_BC_CFRAGMENTATION_UP" : "btag_bc_cfragmentation_up",
        "BTAG_BC_CJETS_UP" : "btag_bc_cjets_up",
        "BTAG_BC_DMUX_UP" : "btag_bc_dmux_up",
        "BTAG_BC_GLUONSPLITTING_UP" : "btag_bc_gluonsplitting_up",
        "BTAG_BC_JETAWAY_UP" : "btag_bc_jetaway_up",
        "BTAG_BC_KSL_UP" : "btag_bc_ksl_up",
        "BTAG_BC_L2C_UP" : "btag_bc_l2c_up",
        "BTAG_BC_LTOTHERS_UP" : "btag_bc_ltothers_up",
        "BTAG_BC_MUDR_UP" : "btag_bc_mudr_up",
        "BTAG_BC_MUPT_UP" : "btag_bc_mupt_up",
        "BTAG_BC_PTREL_UP" : "btag_bc_ptrel_up",
                ##
        #"BTAG_BC_JES_DW" : "btag_bc_jes_down",
        #"BTAG_BC_PILEUP_DW" : "btag_bc_pileup_down",
        #"BTAG_BC_STATISTIC_DW" : "btag_bc_statistic_down",
        ##"BTAG_BC_TYPE3_DW" : "btag_bc_type3_down",
                ## type 3 subsources
        "BTAG_BC_BFRAGMENTATION_DW" : "btag_bc_bfragmentation_down",
        "BTAG_BC_BTEMPCORR_DW" : "btag_bc_btempcorr_down",
        "BTAG_BC_CB_DW" : "btag_bc_cb_down",
        "BTAG_BC_CFRAGMENTATION_DW" : "btag_bc_cfragmentation_down",
        "BTAG_BC_CJETS_DW" : "btag_bc_cjets_down",
        "BTAG_BC_DMUX_DW" : "btag_bc_dmux_down",
        "BTAG_BC_GLUONSPLITTING_DW" : "btag_bc_gluonsplitting_down",
        "BTAG_BC_JETAWAY_DW" : "btag_bc_jetaway_down",
        "BTAG_BC_KSL_DW" : "btag_bc_ksl_down",
        "BTAG_BC_L2C_DW" : "btag_bc_l2c_down",
        "BTAG_BC_LTOTHERS_DW" : "btag_bc_ltothers_down",
        "BTAG_BC_MUDR_DW" : "btag_bc_mudr_down",
        "BTAG_BC_MUPT_DW" : "btag_bc_mupt_down",
        "BTAG_BC_PTREL_DW" : "btag_bc_ptrel_down",
            ##
        #"BTAG_BC_UP_CORR" : "btag_bc_up_correlated",
        #"BTAG_BC_DW_CORR" : "btag_bc_down_correlated",
        #"BTAG_BC_UP_UNCORR" : "btag_bc_up_uncorrelated",
        #"BTAG_BC_DW_UNCORR" : "btag_bc_down_uncorrelated",
        #"BTAG_L_UP" : "btag_l_up",
        #"BTAG_L_DW" : "btag_l_down",
        "BTAG_L_CORR_UP" : "btag_l_correlated_up",
        "BTAG_L_CORR_DW" : "btag_l_correlated_down",
        "BTAG_L_UNCORR_UP" : "btag_l_uncorrelated_up",
        "BTAG_L_UNCORR_DW" : "btag_l_uncorrelated_down",
        "PILEUP_UP" : "PileupUp",
        "PILEUP_DW" : "PileupDown",
        "PREFIRE_UP" : "PrefireUp",
        "PREFIRE_DW" : "PrefireDown",
        "ISR_UP" : "ISRUp",
        "ISR_DW" : "ISRDown",
        "FSR_UP" : "FSRUp",
        "FSR_DW" : "FSRDown",
        "FACTOR_UP" : "FACTORUp",
        "FACTOR_DW" : "FACTORDown",
        "RENORM_UP" : "RENORMUp",
        "RENORM_DW" : "RENORMDown",
        "RENORM_FACTOR_UP" : "RENORM_FACTOR_SAMEUp",
        "RENORM_FACTOR_DW" : "RENORM_FACTOR_SAMEDown",
        "RENORM_UP_FACTOR_DW" : "RENORM_FACTOR_DIFFUp",
        "RENORM_DW_FACTOR_UP" : "RENORM_FACTOR_DIFFDown",
        "deltaQCDdeltaEW_UP" : "EWuncUp",
        "deltaQCDdeltaEW_DW" : "EWuncDown",
        #"deltaQCDdeltaEW" : "EWcorrUp",
        "YUKAWA_UP" : "YukawaUp",
        "YUKAWA_DW" : "YukawaDown",
        "TOPPT_UP" : "TopPtUp",
        "TOPPT_DW" : "TopPtDown",
    }
    for year in ["2016APV", "2016", "2017", "2018"]
}
reweight_sys_opts["2018"].pop("PREFIRE_UP")
reweight_sys_opts["2018"].pop("PREFIRE_DW")

    # systematics that change entire object selection
event_sys_opts = {
    year : {
        "JER_UP" : "JER_UP",
        "JER_DW" : "JER_DW",
        "MET_UP" : "MET_UP",
        "MET_DW" : "MET_DW",
    }
    for year in ["2016APV", "2016", "2017", "2018"]
}
#    # add individual JES systematics
#event_sys_opts["2016APV"].update({"_".join([sys, "UP"]): "_".join([sys, "UP"]) for sys in ind_jec_sys["2016APV"]}) # add up
#event_sys_opts["2016APV"].update({"_".join([sys, "DW"]): "_".join([sys, "DW"]) for sys in ind_jec_sys["2016APV"]}) # add down
#event_sys_opts["2016"].update({"_".join([sys, "UP"]): "_".join([sys, "UP"]) for sys in ind_jec_sys["2016"]}) # add up
#event_sys_opts["2016"].update({"_".join([sys, "DW"]): "_".join([sys, "DW"]) for sys in ind_jec_sys["2016"]}) # add down
#event_sys_opts["2017"].update({"_".join([sys, "UP"]): "_".join([sys, "UP"]) for sys in ind_jec_sys["2017"]}) # add up
#event_sys_opts["2017"].update({"_".join([sys, "DW"]): "_".join([sys, "DW"]) for sys in ind_jec_sys["2017"]}) # add down
#event_sys_opts["2018"].update({"_".join([sys, "UP"]): "_".join([sys, "UP"]) for sys in ind_jec_sys["2018"]}) # add up
#event_sys_opts["2018"].update({"_".join([sys, "DW"]): "_".join([sys, "DW"]) for sys in ind_jec_sys["2018"]}) # add down

    # add regrouped JES systematics
event_sys_opts["2016APV"].update({"_".join([sys, "UP"]).upper(): "_".join([sys, "UP"]) for sys in regroup_jec_sys["2016APV"]}) # add up
event_sys_opts["2016APV"].update({"_".join([sys, "DW"]).upper(): "_".join([sys, "DW"]) for sys in regroup_jec_sys["2016APV"]}) # add down
event_sys_opts["2016"].update({"_".join([sys, "UP"]).upper(): "_".join([sys, "UP"]) for sys in regroup_jec_sys["2016"]}) # add up
event_sys_opts["2016"].update({"_".join([sys, "DW"]).upper(): "_".join([sys, "DW"]) for sys in regroup_jec_sys["2016"]}) # add down
event_sys_opts["2017"].update({"_".join([sys, "UP"]).upper(): "_".join([sys, "UP"]) for sys in regroup_jec_sys["2017"]}) # add up
event_sys_opts["2017"].update({"_".join([sys, "DW"]).upper(): "_".join([sys, "DW"]) for sys in regroup_jec_sys["2017"]}) # add down
event_sys_opts["2018"].update({"_".join([sys, "UP"]).upper(): "_".join([sys, "UP"]) for sys in regroup_jec_sys["2018"]}) # add up
event_sys_opts["2018"].update({"_".join([sys, "DW"]).upper(): "_".join([sys, "DW"]) for sys in regroup_jec_sys["2018"]}) # add down


# dict of name_I_want : name_in_code
    # systematics available to be applied to signal (reweighting)
signal_reweight_opts = {
    year : {
        "LEP_IDtot_UP" : "Lep_IDtotUp",
        "LEP_IDtot_DW" : "Lep_IDtotDown",
        "LEP_IDstat_UP" : "Lep_IDstatUp",
        "LEP_IDstat_DW" : "Lep_IDstatDown",
        "LEP_IDsyst_UP" : "Lep_IDsystUp",
        "LEP_IDsyst_DW" : "Lep_IDsystDown",
        "LEP_ISOtot_UP" : "Lep_ISOtotUp",
        "LEP_ISOtot_DW" : "Lep_ISOtotDown",
        "LEP_ISOstat_UP" : "Lep_ISOstatUp",
        "LEP_ISOstat_DW" : "Lep_ISOstatDown",
        "LEP_ISOsyst_UP" : "Lep_ISOsystUp",
        "LEP_ISOsyst_DW" : "Lep_ISOsystDown",
        "LEP_TRIGtot_UP" : "Lep_TRIGtotUp",
        "LEP_TRIGtot_DW" : "Lep_TRIGtotDown",
        "LEP_TRIGstat_UP" : "Lep_TRIGstatUp",
        "LEP_TRIGstat_DW" : "Lep_TRIGstatDown",
        "LEP_TRIGsyst_UP" : "Lep_TRIGsystUp",
        "LEP_TRIGsyst_DW" : "Lep_TRIGsystDown",
        "LEP_RECOtot_UP" : "Lep_RECOtotUp",
        "LEP_RECOtot_DW" : "Lep_RECOtotDown",
            ##
        #"BTAG_BC_JES_UP" : "btag_bc_jes_up",
        #"BTAG_BC_PILEUP_UP" : "btag_bc_pileup_up",
        #"BTAG_BC_STATISTIC_UP" : "btag_bc_statistic_up",
        ##"BTAG_BC_TYPE3_UP" : "btag_bc_type3_up",
        #"BTAG_BC_JES_DW" : "btag_bc_jes_down",
        #"BTAG_BC_PILEUP_DW" : "btag_bc_pileup_down",
        #"BTAG_BC_STATISTIC_DW" : "btag_bc_statistic_down",
        ##"BTAG_BC_TYPE3_DW" : "btag_bc_type3_down",
            ##
                ## type 3 subsources
        "BTAG_BC_BFRAGMENTATION_UP" : "btag_bc_bfragmentation_up",
        "BTAG_BC_BTEMPCORR_UP" : "btag_bc_btempcorr_up",
        "BTAG_BC_CB_UP" : "btag_bc_cb_up",
        "BTAG_BC_CFRAGMENTATION_UP" : "btag_bc_cfragmentation_up",
        "BTAG_BC_CJETS_UP" : "btag_bc_cjets_up",
        "BTAG_BC_DMUX_UP" : "btag_bc_dmux_up",
        "BTAG_BC_GLUONSPLITTING_UP" : "btag_bc_gluonsplitting_up",
        "BTAG_BC_JETAWAY_UP" : "btag_bc_jetaway_up",
        "BTAG_BC_KSL_UP" : "btag_bc_ksl_up",
        "BTAG_BC_L2C_UP" : "btag_bc_l2c_up",
        "BTAG_BC_LTOTHERS_UP" : "btag_bc_ltothers_up",
        "BTAG_BC_MUDR_UP" : "btag_bc_mudr_up",
        "BTAG_BC_MUPT_UP" : "btag_bc_mupt_up",
        "BTAG_BC_PTREL_UP" : "btag_bc_ptrel_up",
        "BTAG_BC_BFRAGMENTATION_DW" : "btag_bc_bfragmentation_down",
        "BTAG_BC_BTEMPCORR_DW" : "btag_bc_btempcorr_down",
        "BTAG_BC_CB_DW" : "btag_bc_cb_down",
        "BTAG_BC_CFRAGMENTATION_DW" : "btag_bc_cfragmentation_down",
        "BTAG_BC_CJETS_DW" : "btag_bc_cjets_down",
        "BTAG_BC_DMUX_DW" : "btag_bc_dmux_down",
        "BTAG_BC_GLUONSPLITTING_DW" : "btag_bc_gluonsplitting_down",
        "BTAG_BC_JETAWAY_DW" : "btag_bc_jetaway_down",
        "BTAG_BC_KSL_DW" : "btag_bc_ksl_down",
        "BTAG_BC_L2C_DW" : "btag_bc_l2c_down",
        "BTAG_BC_LTOTHERS_DW" : "btag_bc_ltothers_down",
        "BTAG_BC_MUDR_DW" : "btag_bc_mudr_down",
        "BTAG_BC_MUPT_DW" : "btag_bc_mupt_down",
        "BTAG_BC_PTREL_DW" : "btag_bc_ptrel_down",
            ##
        ##"BTAG_BC_UP" : "btag_bc_up",
        ##"BTAG_BC_DW" : "btag_bc_down",
        #"BTAG_BC_UP_CORR" : "btag_bc_up_correlated",
        #"BTAG_BC_DW_CORR" : "btag_bc_down_correlated",
        #"BTAG_BC_UP_UNCORR" : "btag_bc_up_uncorrelated",
        #"BTAG_BC_DW_UNCORR" : "btag_bc_down_uncorrelated",
        ##"BTAG_L_UP" : "btag_l_up",
        ##"BTAG_L_DW" : "btag_l_down",
        "BTAG_L_CORR_UP" : "btag_l_correlated_up",
        "BTAG_L_CORR_DW" : "btag_l_correlated_down",
        "BTAG_L_UNCORR_UP" : "btag_l_uncorrelated_up",
        "BTAG_L_UNCORR_DW" : "btag_l_uncorrelated_down",
        "PILEUP_UP" : "PileupUp",
        "PILEUP_DW" : "PileupDown",
        "PREFIRE_UP" : "PrefireUp",
        "PREFIRE_DW" : "PrefireDown",
        "AH_ISR_UP" : "AH_ISRUp",
        "AH_ISR_DW" : "AH_ISRDown",
        "AH_FSR_UP" : "AH_FSRUp",
        "AH_FSR_DW" : "AH_FSRDown",
        "AH_FACTOR_UP" : "AH_FACTORUp",
        "AH_FACTOR_DW" : "AH_FACTORDown",
        "AH_RENORM_UP" : "AH_RENORMUp",
        "AH_RENORM_DW" : "AH_RENORMDown",
        #"AH_RENORM_FACTOR_UP" : "AH_RENORM_FACTOR_SAMEUp",
        #"AH_RENORM_FACTOR_DW" : "AH_RENORM_FACTOR_SAMEDown",
        #"AH_RENORM_UP_FACTOR_DW" : "AH_RENORM_FACTOR_DIFFUp",
        #"AH_RENORM_DW_FACTOR_UP" : "AH_RENORM_FACTOR_DIFFDown",
        "AH_MTOP1GeV_DW": "mtop171p5",
        "AH_MTOP1GeV_UP": "mtop173p5",
    }
    for year in ["2016APV", "2016", "2017", "2018"]
}
signal_reweight_opts["2018"].pop("PREFIRE_UP")
signal_reweight_opts["2018"].pop("PREFIRE_DW")




# dict of systematic in analyzer to plotting name
sys_to_name = {
    year : {
        #"nosys" : "nosys",
        "EWuncUp" : "deltaQCDdeltaEW_UP",
        "EWuncDown" : "deltaQCDdeltaEW_DW",
        #"EWcorrUp" : "deltaQCDdeltaEW",
        #"EWcorrUp" : "EW_CORR_UP",
        "YukawaUp" : "YUKAWA_UP",
        "YukawaDown" : "YUKAWA_DW",
        "shapeDown" : "SHAPE_DW",
        "shapeUp"   : "SHAPE_UP",
        "TTsubUp" : "EWQCD_TTsub_UP",
        "TTsubDown" : "EWQCD_TTsub_DW",
        "Lep_IDtotUp"   : "LEP_IDtot_UP",
        "Lep_IDtotDown" : "LEP_IDtot_DW",
        "Lep_IDstatUp"   : "LEP_IDstat_UP",
        "Lep_IDstatDown" : "LEP_IDstat_DW",
        "Lep_IDsystUp"   : "LEP_IDsyst_UP",
        "Lep_IDsystDown" : "LEP_IDsyst_DW",
        "Lep_ISOtotUp"   : "LEP_ISOtot_UP",
        "Lep_ISOtotDown" : "LEP_ISOtot_DW",
        "Lep_ISOstatUp"   : "LEP_ISOstat_UP",
        "Lep_ISOstatDown" : "LEP_ISOstat_DW",
        "Lep_ISOsystUp"   : "LEP_ISOsyst_UP",
        "Lep_ISOsystDown" : "LEP_ISOsyst_DW",
        "Lep_TRIGtotUp"   : "LEP_TRIGtot_UP",
        "Lep_TRIGtotDown" : "LEP_TRIGtot_DW",
        "Lep_TRIGstatUp"   : "LEP_TRIGstat_UP",
        "Lep_TRIGstatDown" : "LEP_TRIGstat_DW",
        "Lep_TRIGsystUp"   : "LEP_TRIGsyst_UP",
        "Lep_TRIGsystDown" : "LEP_TRIGsyst_DW",
        "Lep_RECOtotUp"   : "LEP_RECOtot_UP",
        "Lep_RECOtotDown" : "LEP_RECOtot_DW",
            ##
        "btag_bc_jes_up" : "BTAG_BC_JES_UP",
        "btag_bc_pileup_up" : "BTAG_BC_PILEUP_UP",
        "btag_bc_statistic_up" : "BTAG_BC_STATISTIC_UP",
        "btag_bc_type3_up" : "BTAG_BC_TYPE3_UP",
        "btag_bc_jes_down" : "BTAG_BC_JES_DW",
        "btag_bc_pileup_down" : "BTAG_BC_PILEUP_DW",
        "btag_bc_statistic_down" : "BTAG_BC_STATISTIC_DW",
        "btag_bc_type3_down" : "BTAG_BC_TYPE3_DW",
            ##
                ## type 3 subsources
        "btag_bc_bfragmentation_up" : "BTAG_BC_BFRAGMENTATION_UP",
        "btag_bc_btempcorr_up" : "BTAG_BC_BTEMPCORR_UP",
        "btag_bc_cb_up" : "BTAG_BC_CB_UP",
        "btag_bc_cfragmentation_up" : "BTAG_BC_CFRAGMENTATION_UP",
        "btag_bc_cjets_up" : "BTAG_BC_CJETS_UP",
        "btag_bc_dmux_up" : "BTAG_BC_DMUX_UP",
        "btag_bc_gluonsplitting_up" : "BTAG_BC_GLUONSPLITTING_UP",
        "btag_bc_jetaway_up" : "BTAG_BC_JETAWAY_UP",
        "btag_bc_ksl_up" : "BTAG_BC_KSL_UP",
        "btag_bc_l2c_up" : "BTAG_BC_L2C_UP",
        "btag_bc_ltothers_up" : "BTAG_BC_LTOTHERS_UP",
        "btag_bc_mudr_up" : "BTAG_BC_MUDR_UP",
        "btag_bc_mupt_up" : "BTAG_BC_MUPT_UP",
        "btag_bc_ptrel_up" : "BTAG_BC_PTREL_UP",
        "btag_bc_bfragmentation_down" : "BTAG_BC_BFRAGMENTATION_DW",
        "btag_bc_btempcorr_down" : "BTAG_BC_BTEMPCORR_DW",
        "btag_bc_cb_down" : "BTAG_BC_CB_DW",
        "btag_bc_cfragmentation_down" : "BTAG_BC_CFRAGMENTATION_DW",
        "btag_bc_cjets_down" : "BTAG_BC_CJETS_DW",
        "btag_bc_dmux_down" : "BTAG_BC_DMUX_DW",
        "btag_bc_gluonsplitting_down": "BTAG_BC_GLUONSPLITTING_DW",
        "btag_bc_jetaway_down" : "BTAG_BC_JETAWAY_DW",
        "btag_bc_ksl_down" : "BTAG_BC_KSL_DW",
        "btag_bc_l2c_down" : "BTAG_BC_L2C_DW",
        "btag_bc_ltothers_down" : "BTAG_BC_LTOTHERS_DW",
        "btag_bc_mudr_down" : "BTAG_BC_MUDR_DW",
        "btag_bc_mupt_down" : "BTAG_BC_MUPT_DW",
        "btag_bc_ptrel_down" : "BTAG_BC_PTREL_DW",
            ##
        "btag_bc_up" : "BTAG_BC_UP",
        "btag_bc_up_correlated" : "BTAG_BC_CORR_UP",
        "btag_bc_up_uncorrelated" : "BTAG_BC_UNCORR_UP",
        "btag_bc_down" : "BTAG_BC_DW",
        "btag_bc_down_correlated" : "BTAG_BC_CORR_DW",
        "btag_bc_down_uncorrelated" : "BTAG_BC_UNCORR_DW",
        "btag_l_up" : "BTAG_L_UP",
        "btag_l_correlated_up" : "BTAG_L_CORR_UP",
        "btag_l_uncorrelated_up" : "BTAG_L_UNCORR_UP",
        "btag_l_down" : "BTAG_L_DW",
        "btag_l_correlated_down" : "BTAG_L_CORR_DW",
        "btag_l_uncorrelated_down" : "BTAG_L_UNCORR_DW",
        "PileupUp"  : "PILEUP_UP",
        "PileupDown": "PILEUP_DW",
        "PrefireUp" : "PREFIRE_UP",
        "PrefireDown" : "PREFIRE_DW",
        "ISRUp"  : "ISR_UP",
        "ISRDown": "ISR_DW",
        "FSRUp"  : "FSR_UP",
        "FSRDown": "FSR_DW",
        "FACTORUp"  : "FACTOR_UP",
        "FACTORDown": "FACTOR_DW",
        "RENORMUp"  : "RENORM_UP",
        "RENORMDown": "RENORM_DW",
        "RENORM_FACTOR_SAMEUp"  : "RENORM_FACTOR_UP",
        "RENORM_FACTOR_SAMEDown": "RENORM_FACTOR_DW",
        "RENORM_FACTOR_DIFFUp"  : "RENORM_UP_FACTOR_DW",
        "RENORM_FACTOR_DIFFDown": "RENORM_DW_FACTOR_UP",
        "mtopUP"  : "MTOP_UP",
        "mtopDOWN": "MTOP_DW",
        "hdampUP"  : "HDAMP_UP",
        "hdampDOWN": "HDAMP_DW",
        "ueUP"  : "UE_UP",
        "ueDOWN": "UE_DW",
        "JER_UP" : "JER_UP",
        "JER_DW" : "JER_DW",
        "JES_AbsoluteMPFBias_UP" : "JES_AbsoluteMPFBias_UP",
        "JES_AbsoluteMPFBias_DW" : "JES_AbsoluteMPFBias_DW",
        "JES_AbsoluteScale_UP" : "JES_AbsoluteScale_UP",
        "JES_AbsoluteScale_DW" : "JES_AbsoluteScale_DW",
        "JES_AbsoluteStat_UP" : "JES_AbsoluteStat_UP",
        "JES_AbsoluteStat_DW" : "JES_AbsoluteStat_DW",
        "JES_FlavorQCD_UP" : "JES_FlavorQCD_UP",
        "JES_FlavorQCD_DW" : "JES_FlavorQCD_DW",
        "JES_Fragmentation_UP" : "JES_Fragmentation_UP",
        "JES_Fragmentation_DW" : "JES_Fragmentation_DW",
        "JES_PileUpDataMC_UP" : "JES_PileUpDataMC_UP",
        "JES_PileUpDataMC_DW" : "JES_PileUpDataMC_DW",
        "JES_PileUpPtBB_UP" : "JES_PileUpPtBB_UP",
        "JES_PileUpPtBB_DW" : "JES_PileUpPtBB_DW",
        "JES_PileUpPtEC1_UP" : "JES_PileUpPtEC1_UP",
        "JES_PileUpPtEC1_DW" : "JES_PileUpPtEC1_DW",
        "JES_PileUpPtRef_UP" : "JES_PileUpPtRef_UP",
        "JES_PileUpPtRef_DW" : "JES_PileUpPtRef_DW",
        "JES_RelativeBal_UP" : "JES_RelativeBal_UP",
        "JES_RelativeBal_DW" : "JES_RelativeBal_DW",
        "JES_RelativeFSR_UP" : "JES_RelativeFSR_UP",
        "JES_RelativeFSR_DW" : "JES_RelativeFSR_DW",
        "JES_RelativeJEREC1_UP" : "JES_RelativeJEREC1_UP",
        "JES_RelativeJEREC1_DW" : "JES_RelativeJEREC1_DW",
        "JES_RelativePtBB_UP" : "JES_RelativePtBB_UP",
        "JES_RelativePtBB_DW" : "JES_RelativePtBB_DW",
        "JES_RelativePtEC1_UP" : "JES_RelativePtEC1_UP",
        "JES_RelativePtEC1_DW" : "JES_RelativePtEC1_DW",
        "JES_RelativeSample_UP" : "JES_RelativeSample_UP",
        "JES_RelativeSample_DW" : "JES_RelativeSample_DW",
        "JES_RelativeStatEC_UP" : "JES_RelativeStatEC_UP",
        "JES_RelativeStatEC_DW" : "JES_RelativeStatEC_DW",
        "JES_RelativeStatFSR_UP" : "JES_RelativeStatFSR_UP",
        "JES_RelativeStatFSR_DW" : "JES_RelativeStatFSR_DW",
        "JES_SinglePionECAL_UP" : "JES_SinglePionECAL_UP",
        "JES_SinglePionECAL_DW" : "JES_SinglePionECAL_DW",
        "JES_SinglePionHCAL_UP" : "JES_SinglePionHCAL_UP",
        "JES_SinglePionHCAL_DW" : "JES_SinglePionHCAL_DW",
        "JES_TimePtEta_UP" : "JES_TimePtEta_UP",
        "JES_TimePtEta_DW" : "JES_TimePtEta_DW",
        "JES_Total_UP" : "JES_Total_UP",
        "JES_Total_DW" : "JES_Total_DW",
        "JES_Absolute_UP" : "JES_Absolute_UP",
        "JES_Absolute_DW" : "JES_Absolute_DW",
        f"JES_Absolute_{year}_UP" : f"JES_Absolute_{year}_UP",
        f"JES_Absolute_{year}_DW" : f"JES_Absolute_{year}_DW",
        "JES_BBEC1_UP" : "JES_BBEC1_UP",
        "JES_BBEC1_DW" : "JES_BBEC1_DW",
        f"JES_BBEC1_{year}_UP" : f"JES_BBEC1_{year}_UP",
        f"JES_BBEC1_{year}_DW" : f"JES_BBEC1_{year}_DW",
        f"JES_RelativeSample_{year}_UP" : f"JES_RelativeSample_{year}_UP",
        f"JES_RelativeSample_{year}_DW" : f"JES_RelativeSample_{year}_DW",
        "JES_FlavorPureBottom_UP" : "JES_FlavorPureBottom_UP",
        "JES_FlavorPureBottom_DW" : "JES_FlavorPureBottom_DW",
        "JES_FlavorPureBottomOnlyBottomJets_UP" : "JES_FlavorPureBottomOnlyBottomJets_UP",
        "JES_FlavorPureBottomOnlyBottomJets_DW" : "JES_FlavorPureBottomOnlyBottomJets_DW",
        "JES_FlavorPureCharm_UP" : "JES_FlavorPureCharm_UP",
        "JES_FlavorPureCharm_DW" : "JES_FlavorPureCharm_DW",
        "JES_FlavorPureCharmOnlyCharmJets_UP" : "JES_FlavorPureCharmOnlyCharmJets_UP",
        "JES_FlavorPureCharmOnlyCharmJets_DW" : "JES_FlavorPureCharmOnlyCharmJets_DW",
        "JES_FlavorPureQuark_UP" : "JES_FlavorPureQuark_UP",
        "JES_FlavorPureQuark_DW" : "JES_FlavorPureQuark_DW",
        "JES_FlavorPureQuarkOnlyQuarkJets_UP" : "JES_FlavorPureQuarkOnlyQuarkJets_UP",
        "JES_FlavorPureQuarkOnlyQuarkJets_DW" : "JES_FlavorPureQuarkOnlyQuarkJets_DW",
        "JES_FlavorPureGluon_UP" : "JES_FlavorPureGluon_UP",
        "JES_FlavorPureGluon_DW" : "JES_FlavorPureGluon_DW",
        "JES_FlavorPureGluonOnlyGluonJets_UP" : "JES_FlavorPureGluonOnlyGluonJets_UP",
        "JES_FlavorPureGluonOnlyGluonJets_DW" : "JES_FlavorPureGluonOnlyGluonJets_DW",
        "JES_FlavorQCDOnlyLightJets_UP" : "JES_FlavorQCDOnlyLightJets_UP",
        "JES_FlavorQCDOnlyLightJets_DW" : "JES_FlavorQCDOnlyLightJets_DW",
        #"JES_UP" : "JES_UP",
        #"JES_DW" : "JES_DW",
        "MET_UP" : "MET_UP",
        "MET_DW" : "MET_DW",
        "mtop1665": "MTOP6GEV_DW",
        "mtop1695": "MTOP3GEV_DW",
        "mtop1715": "MTOP1GEV_DW",
        "mtop1735": "MTOP1GEV_UP",
        "mtop1755": "MTOP3GEV_UP",
        "mtop1785": "MTOP6GEV_UP",
        "CR1" : "CR1",
        "CR2" : "CR2",
        "erdON" : "erdON",
        "NLOshapeUp"   : "NLOshape_UP",
        "NLOshapeDown" : "NLOshape_DW",
            # A/H signal systematics
        "AH_ISRUp" : "AH_ISR_UP",
        "AH_ISRDown" : "AH_ISR_DW",
        "AH_FSRUp" : "AH_FSR_UP",
        "AH_FSRDown" : "AH_FSR_DW",
        "AH_RENORMUp"   : "AH_RENORM_UP",
        "AH_RENORMDown" : "AH_RENORM_DW",
        "AH_FACTORUp"   : "AH_FACTOR_UP",
        "AH_FACTORDown" : "AH_FACTOR_DW",
        "mtop173p5" : "AH_MTOP_UP",
        "mtop171p5" : "AH_MTOP_DW",
    }
    for year in ["2016APV", "2016", "2017", "2018"]
}
sys_to_name["2018"].pop("PrefireUp")
sys_to_name["2018"].pop("PrefireDown")


    ## dict for writing template names
combine_template_sys_to_name = {
        ## format is name_in_analyzer : (extension_to_topology, only_applies_to_TT)
    year : {
        "nosys" : "",
        "JES_FlavorPureBottomOnlyBottomJets_UP" : "CMS_JEC_13TeV_FlavorPureBottomUp",
        "JES_FlavorPureBottomOnlyBottomJets_DW" : "CMS_JEC_13TeV_FlavorPureBottomDown",
        #"JES_FlavorPureBottomOnlyBottomJets_UP" : "CMS_JEC_13TeV_FlavorPureBottomOnlyBottomJetsUp",
        #"JES_FlavorPureBottomOnlyBottomJets_DW" : "CMS_JEC_13TeV_FlavorPureBottomOnlyBottomJetsDown",
        "JES_FlavorPureBottom_UP" : "CMS_JEC_13TeV_FlavorPureBottomAllJetsUp",
        "JES_FlavorPureBottom_DW" : "CMS_JEC_13TeV_FlavorPureBottomAllJetsDown",
        #"JES_FlavorPureBottom_UP" : "CMS_JEC_13TeV_FlavorPureBottomUp",
        #"JES_FlavorPureBottom_DW" : "CMS_JEC_13TeV_FlavorPureBottomDown",
        "JES_FlavorPureCharmOnlyCharmJets_UP" : "CMS_JEC_13TeV_FlavorPureCharmOnlyCharmJetsUp",
        "JES_FlavorPureCharmOnlyCharmJets_DW" : "CMS_JEC_13TeV_FlavorPureCharmOnlyCharmJetsDown",
        "JES_FlavorPureCharm_UP" : "CMS_JEC_13TeV_FlavorPureCharmUp",
        "JES_FlavorPureCharm_DW" : "CMS_JEC_13TeV_FlavorPureCharmDown",
        "JES_FlavorPureQuarkOnlyQuarkJets_UP" : "CMS_JEC_13TeV_FlavorPureQuarkOnlyQuarkJetsUp",
        "JES_FlavorPureQuarkOnlyQuarkJets_DW" : "CMS_JEC_13TeV_FlavorPureQuarkOnlyQuarkJetsDown",
        "JES_FlavorPureQuark_UP" : "CMS_JEC_13TeV_FlavorPureQuarkUp",
        "JES_FlavorPureQuark_DW" : "CMS_JEC_13TeV_FlavorPureQuarkDown",
        "JES_FlavorPureGluonOnlyGluonJets_UP" : "CMS_JEC_13TeV_FlavorPureGluonOnlyGluonJetsUp",
        "JES_FlavorPureGluonOnlyGluonJets_DW" : "CMS_JEC_13TeV_FlavorPureGluonOnlyGluonJetsDown",
        "JES_FlavorPureGluon_UP" : "CMS_JEC_13TeV_FlavorPureGluonUp",
        "JES_FlavorPureGluon_DW" : "CMS_JEC_13TeV_FlavorPureGluonDown",
        #"JES_FlavorQCDOnlyLightJets_UP" : "CMS_JEC_13TeV_FlavorQCDOnlyLightJetsUp",
        #"JES_FlavorQCDOnlyLightJets_DW" : "CMS_JEC_13TeV_FlavorQCDOnlyLightJetsDown",
        "JES_FlavorQCDOnlyLightJets_UP" : "CMS_JEC_13TeV_FlavorQCDOnNonBottomUp",
        "JES_FlavorQCDOnlyLightJets_DW" : "CMS_JEC_13TeV_FlavorQCDOnNonBottomDown",
            #
        "JES_Absolute_UP" : "CMS_JEC_13TeV_AbsoluteUp",
        "JES_Absolute_DW" : "CMS_JEC_13TeV_AbsoluteDown",
        f"JES_Absolute_{year}_UP" : f"CMS_JEC_13TeV_Absolute_{year}Up",
        f"JES_Absolute_{year}_DW" : f"CMS_JEC_13TeV_Absolute_{year}Down",
        "JES_BBEC1_UP" : "CMS_JEC_13TeV_BBEC1Up",
        "JES_BBEC1_DW" : "CMS_JEC_13TeV_BBEC1Down",
        f"JES_BBEC1_{year}_UP" : f"CMS_JEC_13TeV_BBEC1_{year}Up",
        f"JES_BBEC1_{year}_DW" : f"CMS_JEC_13TeV_BBEC1_{year}Down",
        f"JES_RelativeSample_{year}_UP" : f"CMS_JEC_13TeV_RelativeSample_{year}Up",
        f"JES_RelativeSample_{year}_DW" : f"CMS_JEC_13TeV_RelativeSample_{year}Down",
        "JES_AbsoluteMPFBias_UP" : "CMS_JEC_13TeV_AbsoluteMPFBiasUp",
        "JES_AbsoluteMPFBias_DW" : "CMS_JEC_13TeV_AbsoluteMPFBiasDown",
        "JES_AbsoluteScale_UP" : "CMS_JEC_13TeV_AbsoluteScaleUp",
        "JES_AbsoluteScale_DW" : "CMS_JEC_13TeV_AbsoluteScaleDown",
        "JES_AbsoluteStat_UP" : "CMS_JEC_13TeV_AbsoluteStatUp",
        "JES_AbsoluteStat_DW" : "CMS_JEC_13TeV_AbsoluteStatDown",
        "JES_FlavorQCD_UP" : "CMS_JEC_13TeV_FlavorQCDUp",
        "JES_FlavorQCD_DW" : "CMS_JEC_13TeV_FlavorQCDDown",
        "JES_Fragmentation_UP" : "CMS_JEC_13TeV_FragmentationUp",
        "JES_Fragmentation_DW" : "CMS_JEC_13TeV_FragmentationDown",
        "JES_PileUpDataMC_UP" : "CMS_JEC_13TeV_PileUpDataMCUp",
        "JES_PileUpDataMC_DW" : "CMS_JEC_13TeV_PileUpDataMCDown",
        "JES_PileUpPtBB_UP" : "CMS_JEC_13TeV_PileUpPtBBUp",
        "JES_PileUpPtBB_DW" : "CMS_JEC_13TeV_PileUpPtBBDown",
        "JES_PileUpPtEC1_UP" : "CMS_JEC_13TeV_PileUpPtEC1Up",
        "JES_PileUpPtEC1_DW" : "CMS_JEC_13TeV_PileUpPtEC1Down",
        "JES_PileUpPtRef_UP" : "CMS_JEC_13TeV_PileUpPtRefUp",
        "JES_PileUpPtRef_DW" : "CMS_JEC_13TeV_PileUpPtRefDown",
        "JES_RelativeBal_UP" : "CMS_JEC_13TeV_RelativeBalUp",
        "JES_RelativeBal_DW" : "CMS_JEC_13TeV_RelativeBalDown",
        "JES_RelativeFSR_UP" : "CMS_JEC_13TeV_RelativeFSRUp",
        "JES_RelativeFSR_DW" : "CMS_JEC_13TeV_RelativeFSRDown",
        "JES_RelativeJEREC1_UP" : "CMS_JEC_13TeV_RelativeJEREC1Up",
        "JES_RelativeJEREC1_DW" : "CMS_JEC_13TeV_RelativeJEREC1Down",
        "JES_RelativePtBB_UP" : "CMS_JEC_13TeV_RelativePtBBUp",
        "JES_RelativePtBB_DW" : "CMS_JEC_13TeV_RelativePtBBDown",
        "JES_RelativePtEC1_UP" : "CMS_JEC_13TeV_RelativePtEC1Up",
        "JES_RelativePtEC1_DW" : "CMS_JEC_13TeV_RelativePtEC1Down",
        "JES_RelativeSample_UP" : "CMS_JEC_13TeV_RelativeSampleUp",
        "JES_RelativeSample_DW" : "CMS_JEC_13TeV_RelativeSampleDown",
        "JES_RelativeStatEC_UP" : "CMS_JEC_13TeV_RelativeStatECUp",
        "JES_RelativeStatEC_DW" : "CMS_JEC_13TeV_RelativeStatECDown",
        "JES_RelativeStatFSR_UP" : "CMS_JEC_13TeV_RelativeStatFSRUp",
        "JES_RelativeStatFSR_DW" : "CMS_JEC_13TeV_RelativeStatFSRDown",
        "JES_SinglePionECAL_UP" : "CMS_JEC_13TeV_SinglePionECALUp",
        "JES_SinglePionECAL_DW" : "CMS_JEC_13TeV_SinglePionECALDown",
        "JES_SinglePionHCAL_UP" : "CMS_JEC_13TeV_SinglePionHCALUp",
        "JES_SinglePionHCAL_DW" : "CMS_JEC_13TeV_SinglePionHCALDown",
        "JES_TimePtEta_UP" : "CMS_JEC_13TeV_TimePtEtaUp",
        "JES_TimePtEta_DW" : "CMS_JEC_13TeV_TimePtEtaDown",
        "JES_Total_UP" : "CMS_JEC_13TeV_TotalUp",
        "JES_Total_DW" : "CMS_JEC_13TeV_TotalDown",
        "JER_UP" : "CMS_JER_13TeVUp",
        "JER_DW" : "CMS_JER_13TeVDown",
        "MET_UP" : "CMS_METunclustered_13TeVUp",
        "MET_DW" : "CMS_METunclustered_13TeVDown",
            ##
        "btag_bc_jes_up" : "CMS_eff_b_13TeV_JECUp",
        "btag_bc_jes_down" : "CMS_eff_b_13TeV_JECDown",
        "btag_bc_pileup_up" : "CMS_eff_b_13TeV_PileupUp",
        "btag_bc_pileup_down" : "CMS_eff_b_13TeV_PileupDown",
        "btag_bc_statistic_up" : f"CMS_eff_b_13TeV_Statistic_{year}Up",
        "btag_bc_statistic_down" : f"CMS_eff_b_13TeV_Statistic_{year}Down",
        "btag_bc_type3_up" : "CMS_eff_b_13TeV_Type3Up",
        "btag_bc_type3_down" : "CMS_eff_b_13TeV_Type3Down",
        "btag_bc_bfragmentation_up" : "CMS_eff_b_13TeV_BottomFragmentationUp",
        "btag_bc_bfragmentation_down" : "CMS_eff_b_13TeV_BottomFragmentationDown",
        "btag_bc_btempcorr_up" : "CMS_eff_b_13TeV_BottomTemplateCorrectionUp",
        "btag_bc_btempcorr_down" : "CMS_eff_b_13TeV_BottomTemplateCorrectionDown",
        "btag_bc_cb_up" : "CMS_eff_b_13TeV_JPCorrectionUp",
        "btag_bc_cb_down" : "CMS_eff_b_13TeV_JPCorrectionDown",
        "btag_bc_cfragmentation_up" : "CMS_eff_b_13TeV_CharmFragmentationUp",
        "btag_bc_cfragmentation_down" : "CMS_eff_b_13TeV_CharmFragmentationDown",
        "btag_bc_cjets_up" : "CMS_eff_b_13TeV_CharmTemplateCorrectionUp",
        "btag_bc_cjets_down" : "CMS_eff_b_13TeV_CharmTemplateCorrectionDown",
        "btag_bc_dmux_up" : "CMS_eff_b_13TeV_CharmToMuonBRUp",
        "btag_bc_dmux_down" : "CMS_eff_b_13TeV_CharmToMuonBRDown",
        "btag_bc_gluonsplitting_up" : "CMS_eff_b_13TeV_GluonSplittingUp",
        "btag_bc_gluonsplitting_down" : "CMS_eff_b_13TeV_GluonSplittingDown",
        "btag_bc_jetaway_up" : "CMS_eff_b_13TeV_AwayJetTagUp",
        "btag_bc_jetaway_down" : "CMS_eff_b_13TeV_AwayJetTagDown",
        "btag_bc_ksl_up" : "CMS_eff_b_13TeV_VzeroParticlesUp",
        "btag_bc_ksl_down" : "CMS_eff_b_13TeV_VzeroParticlesDown",
        "btag_bc_l2c_up" : "CMS_eff_b_13TeV_LightCharmRatioUp",
        "btag_bc_l2c_down" : "CMS_eff_b_13TeV_LightCharmRatioDown",
        "btag_bc_ltothers_up" : "CMS_eff_b_13TeV_LifetimeOthersUp",
        "btag_bc_ltothers_down" : "CMS_eff_b_13TeV_LifetimeOthersDown",
        "btag_bc_mudr_up" : "CMS_eff_b_13TeV_MuonDeltaRUp",
        "btag_bc_mudr_down" : "CMS_eff_b_13TeV_MuonDeltaRDown",
        "btag_bc_mupt_up" : "CMS_eff_b_13TeV_MuonPtUp",
        "btag_bc_mupt_down" : "CMS_eff_b_13TeV_MuonPtDown",
        "btag_bc_ptrel_up" : "CMS_eff_b_13TeV_MuonRelativePtUp",
        "btag_bc_ptrel_down" : "CMS_eff_b_13TeV_MuonRelativePtDown",
            ##
        #"btag_bc_up"   : "CMS_eff_b_13TeVUp",
        #"btag_bc_down" : "CMS_eff_b_13TeVDown",
        "btag_bc_up_correlated"   : "CMS_eff_b_13TeVUp",
        "btag_bc_down_correlated" : "CMS_eff_b_13TeVDown",
        #"btag_bc_up_uncorrelated"   : "CMS_eff_b_13TeVUncorrUp",
        #"btag_bc_down_uncorrelated" : "CMS_eff_b_13TeVUncorrDown",
        "btag_bc_up_uncorrelated"   : f"CMS_eff_b_13TeV_{year}Up",
        "btag_bc_down_uncorrelated" : f"CMS_eff_b_13TeV_{year}Down",
        #"btag_l_up"   : "CMS_fake_b_13TeVUp",
        #"btag_l_down" : "CMS_fake_b_13TeVDown",
        "btag_l_up_correlated"   : "CMS_fake_b_13TeVUp",
        "btag_l_down_correlated" : "CMS_fake_b_13TeVDown",
        "btag_l_up_uncorrelated"   : f"CMS_fake_b_13TeV_{year}Up",
        "btag_l_down_uncorrelated" : f"CMS_fake_b_13TeV_{year}Down",
        "Lep_IDtotUp"   : "CMS_eff_LEP_id_totUp",
        "Lep_IDtotDown" : "CMS_eff_LEP_id_totDown",
        "Lep_IDstatUp"   : "CMS_eff_LEP_id_statUp",
        "Lep_IDstatDown" : "CMS_eff_LEP_id_statDown",
        "Lep_IDsystUp"   : "CMS_eff_LEP_id_systUp",
        "Lep_IDsystDown" : "CMS_eff_LEP_id_systDown",
        "Lep_ISOtotUp"   : "CMS_eff_LEP_iso_totUp",
        "Lep_ISOtotDown" : "CMS_eff_LEP_iso_totDown",
        "Lep_ISOstatUp"   : "CMS_eff_LEP_iso_statUp",
        "Lep_ISOstatDown" : "CMS_eff_LEP_iso_statDown",
        "Lep_ISOsystUp"   : "CMS_eff_LEP_iso_systUp",
        "Lep_ISOsystDown" : "CMS_eff_LEP_iso_systDown",
        "Lep_TRIGtotUp"   : "CMS_eff_trigger_LEP_totUp",
        "Lep_TRIGtotDown" : "CMS_eff_trigger_LEP_totDown",
        "Lep_TRIGstatUp"   : "CMS_eff_trigger_LEP_statUp",
        "Lep_TRIGstatDown" : "CMS_eff_trigger_LEP_statDown",
        "Lep_TRIGsystUp"   : "CMS_eff_trigger_LEP_systUp",
        "Lep_TRIGsystDown" : "CMS_eff_trigger_LEP_systDown",
        "Lep_RECOtotUp"   : "CMS_eff_LEP_reco_totUp",
        "Lep_RECOtotDown" : "CMS_eff_LEP_reco_totDown",
        "PileupUp"   : "CMS_pileupUp",
        "PileupDown" : "CMS_pileupDown",
        "PrefireUp"   : "CMS_L1_prefireUp",
        "PrefireDown" : "CMS_L1_prefireDown",
            # EWQCD systematics
        "shapeUp"   : "CHAN_shape_EWQCDUp",
        "shapeDown" : "CHAN_shape_EWQCDDown",
        "TTsubUp" : "CHAN_TTsub_EWQCDUp",
        "TTsubDown" : "CHAN_TTsub_EWQCDDown",
            # TT systematics
        "EWuncUp"   : "EWK_schemeUp",
        "EWuncDown" : "EWK_schemeDown",
        "YukawaUp"   : "EWK_yukawaUp",
        "YukawaDown" : "EWK_yukawaDown",
        "FSRUp"   : "QCDscale_FSR_TTUp",
        "FSRDown" : "QCDscale_FSR_TTDown",
        "ISRUp"   : "QCDscale_ISR_TTUp",
        "ISRDown" : "QCDscale_ISR_TTDown",
        "RENORMUp"   : "QCDscale_MERen_TTUp",
        "RENORMDown" : "QCDscale_MERen_TTDown",
        "FACTORUp"   : "QCDscale_MEFac_TTUp",
        "FACTORDown" : "QCDscale_MEFac_TTDown",
        #"RENORM_FACTOR_SAMEUp"   : "tt_uFuRUp",
        #"RENORM_FACTOR_SAMEDown" : "tt_uFuRDown",
        "ueUP"   : "CMS_UEtune_13TeVUp",
        "ueDOWN" : "CMS_UEtune_13TeVDown",
        "hdampUP"   : "hdamp_TTUp",
        "hdampDOWN" : "hdamp_TTDown",
        #"mtopUP"   : "TMassUp",
        #"mtopDOWN" : "TMassDown",
        "mtop1715" : "tmass_1GeV_TTDown",
        "mtop1735" : "tmass_1GeV_TTUp",
        #"mtop1695" : "tmass_3GeV_TTDown",
        #"mtop1755" : "tmass_3GeV_TTUp",
        "mtop1695" : "tmass_TTDown",
        "mtop1755" : "tmass_TTUp",
        "CR1Up"   : "CR_QCD_TTUp",
        "CR1Down" : "CR_QCD_TTDown",
        "CR2Up"   : "CR_Gluon_TTUp",
        "CR2Down" : "CR_Gluon_TTDown",
        "erdONUp" : "CR_ERD_TTUp",
        "erdONDown" : "CR_ERD_TTDown",
        "NLOshapeUp"   : "NLOshape_TTUp",
        "NLOshapeDown" : "NLOshape_TTDown",
            # A/H signal systematics
        "AH_FSRUp"   : "QCDscale_FSR_AHUp",
        "AH_FSRDown" : "QCDscale_FSR_AHDown",
        "AH_ISRUp"   : "QCDscale_ISR_AHUp",
        "AH_ISRDown" : "QCDscale_ISR_AHDown",
        "AH_RENORMUp"   : "QCDscale_MERen_AHUp",
        "AH_RENORMDown" : "QCDscale_MERen_AHDown",
        "AH_FACTORUp"   : "QCDscale_MEFac_AHUp",
        "AH_FACTORDown" : "QCDscale_MEFac_AHDown",
        "mtop171p5" : "tmass_AHDown",
        "mtop173p5" : "tmass_AHUp",
    }
    for year in ["2016APV", "2016", "2017", "2018"]
}
combine_template_sys_to_name["2018"].pop("PrefireUp")
combine_template_sys_to_name["2018"].pop("PrefireDown")



# dict of systematic types with up/down variation names
sys_groups = {
    year : {
        #"nosys" : ["nosys"],
        "EWK_scheme" : ["EWuncUp", "EWuncDown"],
        "EWK_yukawa" : ["YukawaUp", "YukawaDown"],
        "SHAPE" : ["shapeUp", "shapeDown"],
        "EWQCD_TTsub" : ["TTsubUp", "TTsubDown"],
        "LEP_IDtot" : ["Lep_IDtotUp", "Lep_IDtotDown"],
        "LEP_IDstat" : ["Lep_IDstatUp", "Lep_IDstatDown"],
        "LEP_IDsyst" : ["Lep_IDsystUp", "Lep_IDsystDown"],
        "LEP_ISOtot" : ["Lep_ISOtotUp", "Lep_ISOtotDown"],
        "LEP_ISOstat" : ["Lep_ISOstatUp", "Lep_ISOstatDown"],
        "LEP_ISOsyst" : ["Lep_ISOsystUp", "Lep_ISOsystDown"],
        "LEP_TRIGtot" : ["Lep_TRIGtotUp", "Lep_TRIGtotDown"],
        "LEP_TRIGstat" : ["Lep_TRIGstatUp", "Lep_TRIGstatDown"],
        "LEP_TRIGsyst" : ["Lep_TRIGsystUp", "Lep_TRIGsystDown"],
        "LEP_RECOtot" : ["Lep_RECOtotUp", "Lep_RECOtotDown"],
        #"BTAG_BC" : ["btag_bc_up", "btag_bc_down"],
        "BTAG_BC_CORR" : ["btag_bc_up_correlated", "btag_bc_down_correlated"],
        "BTAG_BC_UNCORR" : ["btag_bc_up_uncorrelated", "btag_bc_down_uncorrelated"],
        "BTAG_BC_JES" : ["btag_bc_jes_up", "btag_bc_jes_down"],
        "BTAG_BC_PILEUP" : ["btag_bc_pileup_up", "btag_bc_pileup_down"],
        "BTAG_BC_STATISTIC" : ["btag_bc_statistic_up", "btag_bc_statistic_down"],
        "BTAG_BC_TYPE3" : ["btag_bc_type3_up", "btag_bc_type3_down"],
                ## type 3 subsources
        "BTAG_BC_BFRAGMENTATION" : ["btag_bc_bfragmentation_up", "btag_bc_bfragmentation_down"],
        "BTAG_BC_BTEMPCORR" : ["btag_bc_btempcorr_up", "btag_bc_btempcorr_down"],
        "BTAG_BC_CB" : ["btag_bc_cb_up", "btag_bc_cb_down"],
        "BTAG_BC_CFRAGMENTATION" : ["btag_bc_cfragmentation_up", "btag_bc_cfragmentation_down"],
        "BTAG_BC_CJETS" : ["btag_bc_cjets_up", "btag_bc_cjets_down"],
        "BTAG_BC_DMUX" : ["btag_bc_dmux_up", "btag_bc_dmux_down"],
        "BTAG_BC_GLUONSPLITTING" : ["btag_bc_gluonsplitting_up", "btag_bc_gluonsplitting_down"],
        "BTAG_BC_JETAWAY" : ["btag_bc_jetaway_up", "btag_bc_jetaway_down"],
        "BTAG_BC_KSL" : ["btag_bc_ksl_up", "btag_bc_ksl_down"],
        "BTAG_BC_L2C" : ["btag_bc_l2c_up", "btag_bc_l2c_down"],
        "BTAG_BC_LTOTHERS" : ["btag_bc_ltothers_up", "btag_bc_ltothers_down"],
        "BTAG_BC_MUDR" : ["btag_bc_mudr_up", "btag_bc_mudr_down"],
        "BTAG_BC_MUPT" : ["btag_bc_mupt_up", "btag_bc_mupt_down"],
        "BTAG_BC_PTREL" : ["btag_bc_ptrel_up", "btag_bc_ptrel_down"],
                ##
        #"BTAG_L" : ["btag_l_up", "btag_l_down"],
        "BTAG_L_CORR" : ["btag_l_correlated_up", "btag_l_correlated_down"],
        "BTAG_L_UNCORR" : ["btag_l_uncorrelated_up", "btag_l_uncorrelated_down"],
        "PILEUP" : ["PileupUp", "PileupDown"],
        "PREFIRE" : ["PrefireUp", "PrefireDown"],
        "ISR" : ["ISRUp", "ISRDown"],
        "FSR" : ["FSRUp", "FSRDown"],
        "FACTOR" : ["FACTORUp", "FACTORDown"],
        "RENORM" : ["RENORMUp", "RENORMDown"],
        #"RENORM_FACTOR" : ["RENORM_FACTOR_SAMEUp", "RENORM_FACTOR_SAMEDown"],
        #"RENORM_UP_FACTOR_DW" : ["RENORM_FACTOR_DIFFUp", None],
        #"RENORM_DW_FACTOR_UP" : ["RENORM_FACTOR_DIFFDown", None],        
        #"MTOP" : ["mtopUP", "mtopDOWN"],
        "HDAMP" : ["hdampUP", "hdampDOWN"],
        "UE" : ["ueUP", "ueDOWN"],
        "JER" : ["JER_UP", "JER_DW"],
        "JES_FlavorPureBottom" : ["JES_FlavorPureBottom_UP", "JES_FlavorPureBottom_DW"],
        "JES_FlavorPureBottomOnlyBottomJets" : ["JES_FlavorPureBottomOnlyBottomJets_UP", "JES_FlavorPureBottomOnlyBottomJets_DW"],
        "JES_FlavorPureCharm" : ["JES_FlavorPureCharm_UP", "JES_FlavorPureCharm_DW"],
        "JES_FlavorPureCharmOnlyCharmJets" : ["JES_FlavorPureCharmOnlyCharmJets_UP", "JES_FlavorPureCharmOnlyCharmJets_DW"],
        "JES_FlavorPureQuark" : ["JES_FlavorPureQuark_UP", "JES_FlavorPureQuark_DW"],
        "JES_FlavorPureQuarkOnlyQuarkJets" : ["JES_FlavorPureQuarkOnlyQuarkJets_UP", "JES_FlavorPureQuarkOnlyQuarkJets_DW"],
        "JES_FlavorPureGluon" : ["JES_FlavorPureGluon_UP", "JES_FlavorPureGluon_DW"],
        "JES_FlavorPureGluonOnlyGluonJets" : ["JES_FlavorPureGluonOnlyGluonJets_UP", "JES_FlavorPureGluonOnlyGluonJets_DW"],
        "JES_FlavorQCDOnlyLightJets" : ["JES_FlavorQCDOnlyLightJets_UP", "JES_FlavorQCDOnlyLightJets_DW"],
        #"JES_AbsoluteMPFBias" : ["JES_AbsoluteMPFBias_UP", "JES_AbsoluteMPFBias_DW"],
        #"JES_AbsoluteScale" : ["JES_AbsoluteScale_UP", "JES_AbsoluteScale_DW"],
        #"JES_AbsoluteStat" : ["JES_AbsoluteStat_UP", "JES_AbsoluteStat_DW"],
        "JES_FlavorQCD" : ["JES_FlavorQCD_UP", "JES_FlavorQCD_DW"],
        #"JES_Fragmentation" : ["JES_Fragmentation_UP", "JES_Fragmentation_DW"],
        #"JES_PileUpDataMC" : ["JES_PileUpDataMC_UP", "JES_PileUpDataMC_DW"],
        #"JES_PileUpPtBB" : ["JES_PileUpPtBB_UP", "JES_PileUpPtBB_DW"],
        #"JES_PileUpPtEC1" : ["JES_PileUpPtEC1_UP", "JES_PileUpPtEC1_DW"],
        #"JES_PileUpPtRef" : ["JES_PileUpPtRef_UP", "JES_PileUpPtRef_DW"],
        "JES_RelativeBal" : ["JES_RelativeBal_UP", "JES_RelativeBal_DW"],
        #"JES_RelativeFSR" : ["JES_RelativeFSR_UP", "JES_RelativeFSR_DW"],
        #"JES_RelativeJEREC1" : ["JES_RelativeJEREC1_UP", "JES_RelativeJEREC1_DW"],
        #"JES_RelativePtBB" : ["JES_RelativePtBB_UP", "JES_RelativePtBB_DW"],
        #"JES_RelativePtEC1" : ["JES_RelativePtEC1_UP", "JES_RelativePtEC1_DW"],
        #"JES_RelativeSample" : ["JES_RelativeSample_UP", "JES_RelativeSample_DW"],
        #"JES_RelativeStatEC" : ["JES_RelativeStatEC_UP", "JES_RelativeStatEC_DW"],
        #"JES_RelativeStatFSR" : ["JES_RelativeStatFSR_UP", "JES_RelativeStatFSR_DW"],
        #"JES_SinglePionECAL" : ["JES_SinglePionECAL_UP", "JES_SinglePionECAL_DW"],
        #"JES_SinglePionHCAL" : ["JES_SinglePionHCAL_UP", "JES_SinglePionHCAL_DW"],
        #"JES_TimePtEta" : ["JES_TimePtEta_UP", "JES_TimePtEta_DW"],
        #"JES_Total" : ["JES_Total_UP", "JES_Total_DW"],
        "JES_Absolute" : ["JES_Absolute_UP", "JES_Absolute_DW"],
        f"JES_Absolute_{year}" : [f"JES_Absolute_{year}_UP", f"JES_Absolute_{year}_DW"],
        "JES_BBEC1" : ["JES_BBEC1_UP", "JES_BBEC1_DW"],
        f"JES_BBEC1_{year}" : [f"JES_BBEC1_{year}_UP", f"JES_BBEC1_{year}_DW"],
        f"JES_RelativeSample_{year}" : [f"JES_RelativeSample_{year}_UP", f"JES_RelativeSample_{year}_DW"],
        "MET" : ["MET_UP", "MET_DW"],
        "MTOP1GEV" : ["mtop1735", "mtop1715"],
        "MTOP3GEV" : ["mtop1755", "mtop1695"],
        "MTOP6GEV" : ["mtop1785", "mtop1665"],
        "CR1" : ["CR1", None],
        "CR2" : ["CR2", None],
        "erdON" : ["erdON", None],
        "NLOshape" : ["NLOshapeUp", "NLOshapeDown"],
            # A/H signal systematics
        "AH_ISR" : ["AH_ISRUp", "AH_ISRDown"],
        "AH_FSR" : ["AH_FSRUp", "AH_FSRDown"],
        "AH_RENORM" : ["AH_RENORMUp", "AH_RENORMDown"],
        "AH_FACTOR" : ["AH_FACTORUp", "AH_FACTORDown"],
        "AH_MTOP" : ["mtop173p5", "mtop171p5"],
    }
    for year in ["2016APV", "2016", "2017", "2018"]
}
sys_groups["2018"].pop("PREFIRE")


final_systypes = {
    year : [
        "EWK_scheme",
        "EWK_yukawa",
        "SHAPE",
        "EWQCD_TTsub",
        "LEP_IDtot",
        "LEP_IDstat",
        "LEP_IDsyst",
        "LEP_ISOtot",
        "LEP_ISOstat",
        "LEP_ISOsyst",
        "LEP_TRIGtot",
        "LEP_TRIGstat",
        "LEP_TRIGsyst",
        "LEP_RECOtot",
        "BTAG_BC_CORR",
        "BTAG_BC_UNCORR",
        "BTAG_BC_JES",
        "BTAG_BC_PILEUP",
        "BTAG_BC_STATISTIC",
        "BTAG_BC_TYPE3",
                ## type 3 subsources
        "BTAG_BC_BFRAGMENTATION",
        "BTAG_BC_BTEMPCORR",
        "BTAG_BC_CB",
        "BTAG_BC_CFRAGMENTATION",
        "BTAG_BC_CJETS",
        "BTAG_BC_DMUX",
        "BTAG_BC_GLUONSPLITTING",
        "BTAG_BC_JETAWAY",
        "BTAG_BC_KSL",
        "BTAG_BC_L2C",
        "BTAG_BC_LTOTHERS",
        "BTAG_BC_MUDR",
        "BTAG_BC_MUPT",
        "BTAG_BC_PTREL",
                ##
        "BTAG_L_CORR",
        "BTAG_L_UNCORR",
        "PILEUP",
        "PREFIRE",
        "ISR",
        "FSR",
        "FACTOR",
        "RENORM",
        "HDAMP",
        "UE",
        "JER",
        "JES_FlavorPureBottomOnlyBottomJets",
        "JES_FlavorQCDOnlyLightJets",
        #"JES_AbsoluteMPFBias",
        #"JES_AbsoluteScale",
        #"JES_AbsoluteStat",
        "JES_FlavorQCD",
        #"JES_Fragmentation",
        #"JES_PileUpDataMC",
        #"JES_PileUpPtBB",
        #"JES_PileUpPtEC1",
        #"JES_PileUpPtRef",
        "JES_RelativeBal",
        #"JES_RelativeFSR",
        #"JES_RelativeJEREC1",
        #"JES_RelativePtBB",
        #"JES_RelativePtEC1",
        #"JES_RelativeSample",
        #"JES_RelativeStatEC",
        #"JES_RelativeStatFSR",
        #"JES_SinglePionECAL",
        #"JES_SinglePionHCAL",
        #"JES_TimePtEta",
        #"JES_Total",
        "JES_Absolute",
        f"JES_Absolute_{year}",
        "JES_BBEC1",
        f"JES_BBEC1_{year}",
        f"JES_RelativeSample_{year}",
        "MET",
        #"MTOP1GEV",
        "MTOP3GEV",
        #"MTOP6GEV",
        "CR1",
        "CR2",
        "erdON",
        "NLOshape",
            # A/H signal systematics
        "AH_ISR",
        "AH_FSR",
        "AH_RENORM",
        "AH_FACTOR",
        ]
    for year in ["2016APV", "2016", "2017", "2018"]
}
final_systypes["2018"].remove("PREFIRE")
