FROM mverzett/urttbar_nano_base:latest

SHELL ["/bin/bash", "-c"]

RUN pip install --no-cache-dir coffea

## Set up X509 proxy to run grid
#ENV X509_USER_PROXY /somewhere

# Commands to run spark
RUN mkdir -p /opt/hadoop/jars && \
    wget -P /opt/hadoop/jars https://repo1.maven.org/maven2/edu/vanderbilt/accre/laurelin/0.5.1/laurelin-0.5.1.jar && \
    wget -P /opt/hadoop/jars https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar && \
    wget -P /opt/hadoop/jars https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar && \
    wget -P /opt/hadoop/jars https://repo1.maven.org/maven2/org/lz4/lz4-java/1.5.1/lz4-java-1.5.1.jar && \
    wget -P /opt/hadoop/jars https://repo1.maven.org/maven2/org/tukaani/xz/1.2/xz-1.2.jar

WORKDIR ${SPARK_HOME}/work-dir

COPY --from=tini-builder /tmp/tini /sbin/tini
COPY ./entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]

LABEL \
  org.label-schema.version="0.1" \
  org.label-schema.build-date=$BUILD_DATE \
  org.label-schema.vcs-url="https://gitlab.cern.ch/db/spark-service/docker-registry.git" \
  org.label-schema.name="SWAN Spark Docker - CERN Spark on Kubernetes" \
  org.label-schema.vendor="CERN" \
  org.label-schema.schema-version="1.0"

