what_to_do = {
    "BTAG_BC_CORR" : {
        "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        "TB" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TQ" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TW" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
    },
    "BTAG_BC_UNCORR" : {
        "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        "TB" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TQ" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TW" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
    },
    "BTAG_L_CORR" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TQ" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TW" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
    },
    "BTAG_L_UNCORR" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TQ" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TW" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
    },
    "EWQCD_SHAPE" : {
        "EWQCD" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
    },
    "FACTOR" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
    },
    "FSR" : {
        "TT" : {"m3" : "smooth", "m4" : "flat", "e3" : "smooth", "e4" : "flat"},
    },
    "HDAMP" : {
        "TT" : {"m3" : "flat", "m4" : "smooth", "e3" : "flat", "e4" : "smooth"},
    },
    "ISR" : {
        "TT" : {"m3" : "smooth", "m4" : "flat", "e3" : "smooth", "e4" : "flat"},
    },
    "JER" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_Absolute" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TW" : {"m3" : "flat", "m4" : "smooth", "e3" : "flat", "e4" : "smooth"},
    },
    "JES_Absolute_2016APV" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_Absolute_2016" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_Absolute_2017" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_Absolute_2018" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_AbsoluteMPFBias" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_AbsoluteScale" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_AbsoluteStat" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_BBEC1" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_BBEC1_2016APV" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_BBEC1_2016" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_BBEC1_2017" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_BBEC1_2018" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_FlavorQCD" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_Fragmentation" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_PileUpDataMC" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TW" : {"m3" : "flat", "m4" : "smooth", "e3" : "flat", "e4" : "smooth"},
    },
    "JES_PileUpPtBB" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_PileUpPtEC1" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_PileUpPtRef" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_RelativeBal" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TQ" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TW" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
    },
    "JES_RelativeFSR" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_RelativeJEREC1" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_RelativePtBB" : {
        "TT" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_RelativePtEC1" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_RelativeSample" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_RelativeSample_2016APV" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_RelativeSample_2016" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_RelativeSample_2017" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_RelativeSample_2018" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TQ" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_RelativeStatEC" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_RelativeStatFSR" : {
        "TT" : {"m3" : "flat", "m4" : "smooth", "e3" : "flat", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_SinglePionECAL" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_SinglePionHCAL" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_TimePtEta" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "JES_Total" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "LEP_RECO" : {
        "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        "TB" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TQ" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TW" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
    },
    "LEP_TRIG" : {
        "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        "TB" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TQ" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TW" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
    },
    "MET" : {
        "TT" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "MTOP3GEV" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
    },
    "PILEUP" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        "TQ" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
        "TW" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
    },
    "RENORM" : {
        "TT" : {"m3" : "smooth", "m4" : "smooth", "e3" : "smooth", "e4" : "smooth"},
    },
    "UE" : {
        "TT" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
    },
    "deltaQCDdeltaEW" : {
        "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
    },
}
