treatment = {
    "2016APV" : {
        "BTAG_BC_CORR" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "BTAG_BC_UNCORR" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "BTAG_L_CORR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "BTAG_L_UNCORR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "EWQCD_SHAPE" : {
            "EWQCD" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "FACTOR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "FSR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "HDAMP" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "ISR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "JER" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_Absolute" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "symm", "e3" : "flat", "e4" : "symm"},
        },
        "JES_Absolute_2016APV" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_AbsoluteMPFBias" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_AbsoluteScale" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_AbsoluteStat" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_BBEC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_BBEC1_2016APV" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_FlavorQCD" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_Fragmentation" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_PileUpDataMC" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "symm", "e3" : "flat", "e4" : "symm"},
        },
        "JES_PileUpPtBB" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_PileUpPtEC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_PileUpPtRef" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeBal" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeFSR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeJEREC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativePtBB" : {
            "TT" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativePtEC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeSample" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeSample_2016APV" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeStatEC" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeStatFSR" : {
            "TT" : {"m3" : "flat", "m4" : "symm", "e3" : "flat", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_SinglePionECAL" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_SinglePionHCAL" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_TimePtEta" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_Total" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "LEP_IDtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_IDstat" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_IDsyst" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_ISOtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_ISOstat" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_ISOsyst" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_TRIGtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_TRIGstat" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_TRIGsyst" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_RECOtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        #"LEP_RECO" : {
        #    "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        #    "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #},
        #"LEP_TRIG" : {
        #    "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        #    "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #},
        "MET" : {
            "TT" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "MTOP3GEV" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "PILEUP" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "PREFIRE" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "RENORM" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "UE" : {
            "TT" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "YUKAWA" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        },
        "deltaQCDdeltaEW" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        },
    },
    "2016" : {
        "BTAG_BC_CORR" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "BTAG_BC_UNCORR" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "BTAG_L_CORR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "BTAG_L_UNCORR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "EWQCD_SHAPE" : {
            "EWQCD" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "FACTOR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "smooth"},
        },
        "FSR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "HDAMP" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "ISR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "JER" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_Absolute" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "symm", "e3" : "flat", "e4" : "symm"},
        },
        "JES_Absolute_2016" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_AbsoluteMPFBias" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_AbsoluteScale" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_AbsoluteStat" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_BBEC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_BBEC1_2016" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_FlavorQCD" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_Fragmentation" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_PileUpDataMC" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "symm", "e3" : "flat", "e4" : "symm"},
        },
        "JES_PileUpPtBB" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_PileUpPtEC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_PileUpPtRef" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeBal" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeFSR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeJEREC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativePtBB" : {
            "TT" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativePtEC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeSample" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeSample_2016" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeStatEC" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeStatFSR" : {
            "TT" : {"m3" : "flat", "m4" : "symm", "e3" : "flat", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_SinglePionECAL" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_SinglePionHCAL" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_TimePtEta" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_Total" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "LEP_IDtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_IDstat" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_IDsyst" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_ISOtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_ISOstat" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_ISOsyst" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_TRIGtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_TRIGstat" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_TRIGsyst" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_RECOtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        #"LEP_RECO" : {
        #    "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        #    "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #},
        #"LEP_TRIG" : {
        #    "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        #    "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #},
        "MET" : {
            "TT" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "MTOP3GEV" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "PILEUP" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "PREFIRE" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "RENORM" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "UE" : {
            "TT" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "YUKAWA" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        },
        "deltaQCDdeltaEW" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        },
    },
    "2017" : {
        "BTAG_BC_CORR" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "BTAG_BC_UNCORR" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "BTAG_L_CORR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "BTAG_L_UNCORR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "EWQCD_SHAPE" : {
            "EWQCD" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "FACTOR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "smooth"},
        },
        "FSR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "HDAMP" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "ISR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "JER" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_Absolute" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "symm", "e3" : "flat", "e4" : "symm"},
        },
        "JES_Absolute_2017" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_AbsoluteMPFBias" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_AbsoluteScale" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_AbsoluteStat" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_BBEC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "symm", "e3" : "flat", "e4" : "symm"},
        },
        "JES_BBEC1_2017" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_FlavorQCD" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "JES_Fragmentation" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_PileUpDataMC" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "symm", "e3" : "flat", "e4" : "symm"},
        },
        "JES_PileUpPtBB" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_PileUpPtEC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_PileUpPtRef" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeBal" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeFSR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeJEREC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativePtBB" : {
            "TT" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativePtEC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeSample" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeSample_2017" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeStatEC" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeStatFSR" : {
            "TT" : {"m3" : "flat", "m4" : "symm", "e3" : "flat", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_SinglePionECAL" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_SinglePionHCAL" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_TimePtEta" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_Total" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "LEP_IDtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_IDstat" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_IDsyst" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_ISOtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_ISOstat" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_ISOsyst" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_TRIGtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_TRIGstat" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_TRIGsyst" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_RECOtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        #"LEP_RECO" : {
        #    "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        #    "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #},
        #"LEP_TRIG" : {
        #    "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        #    "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #},
        "MET" : {
            "TT" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "MTOP3GEV" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "PILEUP" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "PREFIRE" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "RENORM" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "UE" : {
            "TT" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "YUKAWA" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        },
        "deltaQCDdeltaEW" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        },
    },
    "2018" : {
        "BTAG_BC_CORR" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "BTAG_BC_UNCORR" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "BTAG_L_CORR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "BTAG_L_UNCORR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "EWQCD_SHAPE" : {
            "EWQCD" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "FACTOR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "FSR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "HDAMP" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "ISR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "JER" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_Absolute" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "JES_Absolute_2018" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "JES_AbsoluteMPFBias" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_AbsoluteScale" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_AbsoluteStat" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_BBEC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "symm", "e3" : "flat", "e4" : "symm"},
        },
        "JES_BBEC1_2018" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "JES_FlavorQCD" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "JES_Fragmentation" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_PileUpDataMC" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "symm", "e3" : "flat", "e4" : "symm"},
        },
        "JES_PileUpPtBB" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_PileUpPtEC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_PileUpPtRef" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeBal" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "JES_RelativeFSR" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeJEREC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativePtBB" : {
            "TT" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativePtEC1" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeSample" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeSample_2018" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "JES_RelativeStatEC" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_RelativeStatFSR" : {
            "TT" : {"m3" : "flat", "m4" : "symm", "e3" : "flat", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_SinglePionECAL" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_SinglePionHCAL" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_TimePtEta" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "JES_Total" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "LEP_IDtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_IDstat" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_IDsyst" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_ISOtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_ISOstat" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_ISOsyst" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_TRIGtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_TRIGstat" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_TRIGsyst" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "LEP_RECOtot" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        #"LEP_RECO" : {
        #    "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        #    "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #},
        #"LEP_TRIG" : {
        #    "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        #    "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #    "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        #},
        "MET" : {
            "TT" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TB" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TQ" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
            "TW" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "MTOP3GEV" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "PILEUP" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TB" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TQ" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
            "TW" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "RENORM" : {
            "TT" : {"m3" : "symm", "m4" : "symm", "e3" : "symm", "e4" : "symm"},
        },
        "UE" : {
            "TT" : {"m3" : "flat", "m4" : "flat", "e3" : "flat", "e4" : "flat"},
        },
        "YUKAWA" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        },
        "deltaQCDdeltaEW" : {
            "TT" : {"m3" : "raw", "m4" : "raw", "e3" : "raw", "e4" : "raw"},
        },
    },
}
