## for good colors search here http://colorbrewer2.org/#type=qualitative&scheme=Set1&n=6

styles = {
#   'EWK' : {
#      'legendstyle' : 'f',
#      'drawstyle' : 'hist',
#      'fillcolor' : 417,
#      #'fillcolor' : ROOT.kGreen+1,
#      'linecolor' : 'black',
#            'linewidth' : 1,
#      'name' : "EW",
#      'fillstyle': 'solid',
#      },
#   '[WZ][WZ]' : {
#      'legendstyle' : 'f',
#      'drawstyle' : 'hist',
#      'fillcolor' : '#9fcc18',
#      'linecolor' : 'black',
#            'linewidth' : 1,
#      'name' : "VV",
#      #'name' : "diboson",
#      'fillstyle': 'solid',
#      },
#   'WJets*' : {
#      'legendstyle' : 'f',
#      'drawstyle' : 'hist',
#      'fillcolor' : '#144f13',
#      'linecolor' : 'black',
#      'name' : "W+jets",
#      'fillstyle': 'solid',
#      },
#   'ZJets*' : {
#      'legendstyle' : 'f',
#      'drawstyle' : 'hist',
#      'fillcolor' : '#18cc18',
#      'linecolor' : 'black',
#      'name' : "Z+jets",
#      'fillstyle': 'solid',
#      },
#   'single*' : {
#      'legendstyle' : 'f',
#      'drawstyle' : 'hist',
#      'fillcolor' : '#FFD700',
#      'linecolor' : 'black',
#            'linewidth' : 1,
#      'name' : "single top",
#      'fillstyle': 'solid',
#      },
#   'data*' : {
#      'legendstyle' : 'p',
#      'drawstyle' : 'E0 X0',
#      'markerstyle' : 20,
#      #'markersize'  : 2,
#      'name' : "Observed",
#    },
    'tt*' : {
        #'legendstyle' : 'f',
        #'drawstyle' : 'hist',
        'facecolor' : '#e41a1c', ## red
        #'linewidth' : 1,
        'name' : "$t\\bart$",
        #'fillstyle': 'solid',
    },
#   'tt[WZ]*' : {
#      'legendstyle' : 'f',
#      'drawstyle' : 'hist',
#      'fillcolor' : '#cc8d18',
#      #'fillcolor' : ROOT.kOrange + 1,
#      'linecolor' : 'black',
#            'linewidth' : 1,
#      'name' : "ttV",
#      'fillstyle': 'solid',
#      },
#   'QCD*' : {
#      'legendstyle' : 'f',
#      'drawstyle' : 'hist',
#      'fillcolor' : 'c',
#      #'fillcolor' : ROOT.kGray,
#      'linecolor' : 'black',
#            'linewidth' : 1,
#      'name' : "QCD",
#      'fillstyle': 'solid',
#      },
}
