#export jobid=NanoAODv6
#export jobid=Testing
#export jobid=jpt30_ljpt0_leppt30
#export jobid=jpt30_ljpt0_leppt30_cutBasedEl
#export jobid=jpt30_ljpt0_leppt30_mvaEl
#export jobid=jpt30_ljpt50_MT40_cutBasedEl
#export jobid=ULnanoAOD
export jobid=ULnanoAOD_jpt30_ljpt50_MT40_cutBasedEl
#jobid=NanoAODv6_Testing
